- name: ensure packages are installed
  become: yes
  apt:
    name:
      - ntp
      - neovim
      - vim
      - nfs-common
    state: present
    update_cache: yes
  when: ansible_distribution == "Debian"

- name: Ensure NTP is enabled
  ansible.builtin.service:
    name: ntp
    state: started
