- name: ensure packages are installed
  become: 'yes'
  apt:
    name:
      - ntp
      - neovim
      - vim
      - nfs-common
    state: present
    update_cache: yes
  when: ansible_distribution == "Debian"

- name: ensure services are started
  become: 'yes'
  ansible.builtin.service:
    name: ntp
    state: started

- name: Ensure group 'ansible' exists with gid 2000
  ansible.builtin.group:
    name: ansible
    state: present
    gid: 2000

- name: Add the user 'ansible' with gid 2000
  ansible.builtin.user:
    name: 'ansible'
    comment: 'Ansible Daemon'
    uid: 2000
    group: 'ansible'

- name: add ssh key to 'ansible' user
  authorized_key:
    user: 'ansible'
    state: 'present'
    key: '{{ item }}'
  with_items: '{{ ansible_ssh_keys }}'

- name: test for ntfy line in /etc/pam.d/sshd
  shell: grep -c "ntfy-ssh-login" /etc/pam.d/sshd || true
  register: grep_pamd_sshd

- name: add ntfy-ssh line to /etc/pam.d/sshd
  become: 'yes'
  lineinfile:
    dest: '/etc/pam.d/sshd'
    line: 'session optional pam_exec.so /usr/bin/ntfy-ssh-login.sh'
  when: grep_pamd_sshd.stdout == "0"

- name: copy ntfy-ssh-login.sh script
  become: 'yes'
  ansible.builtin.template:
    src: 'ntfy-ssh-login.sh.j2'
    dest: '/usr/bin/ntfy-ssh-login.sh'
    owner: 'ansible'
    group: 'ansible'
    mode: 'u=wxr,g=xr,o=x'
