version: '3.7'

services:
  wael:
    # 2022-10-12
    image: wael:
    environment:
      TZ: 'America/New_York'
    ports:
      - "3000"
    env_file:
      - "~/docker/services/wael/secret.env"
    volumes:
      - "~/docker/data/wael/data/:/workspace/prisma/data/:rw"
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wael.rule=Host(`wael.zah.rocks`)"
      - "traefik.http.routers.wael.entrypoints=websecure"
      - "traefik.http.routers.wael.tls.certresolver=myresolver"
