---

services:
  baikal:
    # 2022-11-22
    image: ckulka/baikal:0.9.2-nginx@sha256:f35672eb383e825c6a01cd93c5c7f466d0bae9092cf5f1839ff5b2ec1e71fc65
    environment:
      BAIKAL_SERVERNAME: 'dav.zah.rocks'
    volumes:
      - "~/docker/data/baikal/specific/:/var/www/baikal/Specific/:rw"
      - "~/docker/data/baikal/config/:/var/www/baikal/config/:rw"
    ports:
      - "80"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.baikal.rule=Host(`dav.zah.rocks`)"
      - "traefik.http.routers.baikal.entrypoints=websecure"
      - "traefik.http.routers.baikal.tls.certresolver=myresolver"

