---

- name: set compose project name in bashrc
  ansible.builtin.lineinfile:
    dest: '~/.bashrc'
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
    state: 'present'
  with_items:
    - regexp: '^export COMPOSE_PROJECT_NAME="labchicanery"$'
      line: 'export COMPOSE_PROJECT_NAME="labchicanery"'

- name: ensure packages are installed
  become: 'yes'
  ansible.builtin.apt:
    name:
      - 'python3'
      - 'python3-pip'
      - 'libpq-dev'
    state: 'present'
    update_cache: 'yes'

- name: install python packages for managing docker
  ansible.builtin.pip:
    name:
      - 'docker'
      - 'docker-compose'
      - 'psycopg2'

- name: ensure .extra_profiles dir exists
  ansible.builtin.file:
    owner: 'guest'
    group: 'guest'
    state: 'directory'
    mode: 'u=rwx'
    path: '/home/guest/.extra_configs'

- name: add andrew extra_profile config
  ansible.builtin.template:
    owner: 'guest'
    group: 'guest'
    src: 'andrew.sh.j2'
    dest: '/home/guest/.extra_configs/andrew'
    mode: '0644'

- name: add james extra_profile config
  ansible.builtin.template:
    owner: 'guest'
    group: 'guest'
    src: 'james.sh.j2'
    dest: '/home/guest/.extra_configs/james'
    mode: '0644'

- name: install and configure rclone
  ansible.builtin.include_tasks: setup_rclone.yml

- name: Run 'docker-compose down' for mc servers
  environment:
    COMPOSE_PROJECT_NAME: 'labchicanery'
  community.docker.docker_compose:
    project_src: '~/minecraft'
    state: 'absent'
    services:
      - 'labchicanery-survival'
  ignore_errors: 'yes'

- name: ensure ~/minecraft dir DOESNT exist
  ansible.builtin.file:
    path: '~/minecraft'
    state: 'absent'

- name: ensure ~/terraria dir DOESNT exist
  ansible.builtin.file:
    path: '/home/guest/terraria'
    state: 'absent'

# use instead of rsync due to weird perms issue
- name: copy minecraft dir to remote
  ansible.builtin.copy:
    src: '../games/minecraft/'
    dest: '~/minecraft/'
    remote_src: 'no'
    owner: 'guest'
    group: 'guest'
    mode: 'preserve'

- name: ensure minecraft data dirs exist
  ansible.builtin.file:
    path: '{{ item }}'
    owner: 'guest'
    group: 'guest'
    mode: '0755'
    state: 'directory'
  with_items:
    - '~/minecraft/data/survival'
    - '~/minecraft/data/creative'
    - '~/minecraft/data/skyblock'
    - '~/minecraft/data/postgres'

- name: ensure minecraft conf dirs exist
  ansible.builtin.file:
    path: '{{ item }}'
    owner: 'guest'
    group: 'guest'
    mode: '0755'
    state: 'directory'
  with_items:
    - '~/minecraft/data/velocity/config/plugins/huskchat'
    - '~/minecraft/data/velocity/config/plugins/luckperms'

- name: create symbolic links for world data dirs
  become: 'yes'
  ansible.builtin.file:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: 'guest'
    group: 'guest'
    state: 'link'
  with_items:
    - src: '/mnt/eagle/games/labchicanery-minecraft/survival/data'
      dest: '/home/guest/minecraft/data/survival/data'
    - src: '/mnt/eagle/games/labchicanery-minecraft/creative/data'
      dest: '/home/guest/minecraft/data/creative/data'
    - src: '/mnt/eagle/games/labchicanery-minecraft/skyblock/data'
      dest: '/home/guest/minecraft/data/skyblock/data'
    - src: '/mnt/eagle/games/labchicanery-minecraft/postgres/data'
      dest: '/home/guest/minecraft/data/postgres/data'

- name: docker-compose.yml template
  ansible.builtin.template:
    src: 'mc/docker-compose.yml.j2'
    dest: '/home/guest/minecraft/docker-compose.yml'
    mode: '0600'

- name: postgres secret.env template
  ansible.builtin.template:
    src: 'postgres.env.j2'
    dest: '/home/guest/minecraft/postgres-secret.env'
    mode: '0600'

- name: configure mc plugins
  ansible.builtin.include_tasks: configure_mc_plugins.yml

- name: Run 'docker-compose up' for postgres first
  environment:
    COMPOSE_PROJECT_NAME: 'labchicanery'
  community.docker.docker_compose:
    project_src: '~/minecraft'
    remove_orphans: 'yes'
    state: 'present'
    recreate: 'smart'
    services:
      - 'postgres'

- name: configure postgres database
  ansible.builtin.include_tasks: configure_postgres.yml

- name: Run 'docker-compose up' for mc servers
  environment:
    COMPOSE_PROJECT_NAME: 'labchicanery'
  community.docker.docker_compose:
    project_src: '~/minecraft'
    remove_orphans: 'yes'
    state: 'present'
    recreate: 'smart'
    services:
      - 'proxy'
      - 'creative'
      - 'survival'
      - 'postgres'
