---

- name: set compose project name in bashrc
  ansible.builtin.lineinfile:
    dest: '~/.bashrc'
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
    state: 'present'
  with_items:
    - regexp: '^export COMPOSE_PROJECT_NAME="labchicanery"$'
      line: 'export COMPOSE_PROJECT_NAME="labchicanery"'

- name: install python packages for managing docker
  ansible.builtin.pip:
    name:
      - 'docker'
      - 'docker-compose'

- name: ensure .extra_profiles dir exists
  ansible.builtin.file:
    owner: 'guest'
    group: 'guest'
    state: 'directory'
    mode: 'u=rwx'
    path: '/home/guest/.extra_configs'

- name: add andrew extra_profile config
  ansible.builtin.template:
    owner: 'guest'
    group: 'guest'
    src: 'andrew.sh.j2'
    dest: '/home/guest/.extra_configs/andrew'
    mode: '0644'

- name: add james extra_profile config
  ansible.builtin.template:
    owner: 'guest'
    group: 'guest'
    src: 'james.sh.j2'
    dest: '/home/guest/.extra_configs/james'
    mode: '0644'

- name: Run 'docker-compose down' for mc servers
  environment:
    COMPOSE_PROJECT_NAME: 'labchicanery'
  community.docker.docker_compose:
    project_src: '~/minecraft'
    state: 'absent'
    services:
      - 'labchicanery-survival'
  ignore_errors: 'yes'

- name: ensure ~/minecraft dir DOESNT exist
  ansible.builtin.file:
    path: '~/minecraft'
    state: 'absent'

- name: ensure ~/terraria dir DOESNT exist
  ansible.builtin.file:
    path: '/home/guest/terraria'
    state: 'absent'

# use instead of rsync due to weird perms issue
- name: copy minecraft dir to remote
  ansible.builtin.copy:
    src: '../games/minecraft/'
    dest: '~/minecraft/'
    remote_src: 'no'
    owner: 'guest'
    group: 'guest'
    mode: 'preserve'

- name: ensure minecraft data dirs exist
  ansible.builtin.file:
    path: '{{ item }}'
    owner: 'guest'
    group: 'guest'
    mode: '0755'
    state: 'directory'
  with_items:
    - '~/minecraft/data'
    - '~/minecraft/data/labchicanery-survival'
    - '~/minecraft/data/labchicanery-creative'
    - '~/minecraft/data/labchicanery-skyblock'

- name: create symbolic links for world data dirs
  ansible.builtin.file:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: 'guest'
    group: 'guest'
    state: 'link'
  with_items:
    - src: '/mnt/eagle/games/minecraft/labchicanery-survival/data'
      dest: '~/minecraft/data/labchicanery-survival/data'
    - src: '/mnt/eagle/games/minecraft/labchicanery-creative/data'
      dest: '~/minecraft/data/labchicanery-creative/data'
    - src: '/mnt/eagle/games/minecraft/labchicanery-skyblock/data'
      dest: '~/minecraft/data/labchicanery-skyblock/data'

- name: Run 'docker-compose up' for mc servers
  environment:
    COMPOSE_PROJECT_NAME: 'labchicanery'
  community.docker.docker_compose:
    project_src: '~/minecraft'
    remove_orphans: 'yes'
    state: 'present'
    recreate: 'smart'
    services:
      - 'mcrouter'
      - 'labchicanery-creative'
      - 'labchicanery-survival'
