---
- include_tasks: setup_system.yml
- include_tasks: setup_nfs.yml

- name: ensures minecraft service dirs exist
  file:
    state: 'directory'
    mode: 'u=rwx,go=rx'
    path: '{{ item.value.dest }}'
    recurse: true
  loop: "{{ lookup('dict', worlds) }}"

- name: rsync worlds
  synchronize:
    archive: 'yes'
    compress: 'yes'
    recursive: 'yes'
    src: '{{ item.value.src }}'
    dest: '{{ item.value.dest }}'
  loop: "{{ lookup('dict', worlds) }}"
  delegate_to: "{{ inventory_hostname }}"

- include_tasks: setup_proxy_service.yml
- include_tasks: setup_survival_server.yml
#- include_tasks: setup_creative_server
- include_tasks: setup_mcrcon.yml

- name: reload systemctl
  become: yes
  systemd:
    daemon_reload: yes

- name: start minecraft services
  become: yes
  service:
    name: '{{ item }}'
    state: started
  with_items:
    - velocity.service
    - survival_server.service
    #- creative_server.service
