version: '3.8'

services:
  unifi-controller:
    # 2023-02-28
    image: linuxserver/unifi-controller:7.2.92@sha256:c70bf1c80a927ae1cf34dd83dbfea7b9e8c61efd8272d32a59cf06f6ada75ef3
    environment:
      MEM_LIMIT: '1024M'
    ports:
      - "3478:3478/udp"
      - "10001:10001/udp"
      - "8081:8080"
      - "8444:8443"
    volumes:
      - "~/docker/data/unifi-controller/:/config/:rw"
    restart: unless-stopped
