---

services:
  monicahq:
    image: docker.io/library/monica:4.1.2-apache@sha256:9d914445b4aeb450e4eb23ef9db0a4e6a9085f4e8a21459868c8caf7a68add35
    ports:
      - "80"
    environment:
      APP_ENV: 'production'
      APP_DEBUG: 'false'
      APP_URL: 'https://monicahq.zah.rocks'
    env_file:
      - "~/docker/services/monicahq/secret.env"
    volumes:
      - "~/docker/data/monicahq/data/:/var/www/html/storage/"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.monicahq.rule=Host(`monicahq.zah.rocks`)"
      - "traefik.http.routers.monicahq.entrypoints=websecure"
      - "traefik.http.routers.monicahq.tls.certresolver=myresolver"
