---
services:
  keycloak25:
    # 2024-10-03
    image: quay.io/keycloak/keycloak@sha256:82c5b7a110456dbd42b86ea572e728878549954cc8bd03cd65410d75328095d2
    command:
      - "start"
      - "--http-enabled=true"
      - "--hostname=idp25.zah.rocks"
      - "--hostname-admin=idp25.zah.rocks"
      - "--proxy=passthrough"
    env_file:
      "~/docker/services/keycloak25/secret.env"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak25.rule=Host(`idp25.zah.rocks`)"
      - "traefik.http.routers.keycloak25.entrypoints=websecure"
      - "traefik.http.routers.keycloak25.tls.certresolver=myresolver"
    restart: unless-stopped
