version: "3"

services:
  mcrouter:
    image: itzg/mc-router:1.16.1@sha256:9fbe6e1877108c69999de7c0ee54837f4d11fbc9b25a4ea9a80741af4fd3202f
    ports:
      - '25565:25565'
    command: --mapping=survival.mc.zah.rocks=labchicanery-survival:25565

  labchicanery-survival:
    image: itzg/minecraft-server:java17-jdk
    environment:
      UID: 1010
      GID: 1010
      VERSION: '1.19.2'
      TYPE: 'FABRIC'
      EULA: 'TRUE'
      ENABLE_AUTOPAUSE: 'TRUE'
      DIFFICULTY: 'hard'
      MOTD: 'Testing'
      WHITELIST: '65d05271-5ef9-4a49-af14-88079400b83e'
      ENFORCE_WHITELIST: 'TRUE'
      #OPS: 'user1,user2'
      OVERRIDE_OPS: 'TRUE'
      ENABLE_RCON: 'TRUE'
      RCON_PASSWORD: '2b65f1d6802eb8b5a513d020959477d92d3ec514b006810ca953fe45978c524d'
      MODE: 'survival'
      PVP: 'FALSE'
      LEVEL: 'labchicanery-survival'
      SERVER_NAME: 'LabChicanery-Survival'
      USE_AIKAR_FLAGS: 'FALSE'
      MEMORY: '8G'
      TZ: 'America/New_York'
      MAX_TICK_TIME: '-1'
      MODS: '/mods'
      # TODO: change to proper seed
      SEED: '1278040446' # 425,-600
      # phosphor instead of starlight
      # textile_backup has to be modified manually for 1.19.2, TODO: remove from ./mods/ at some point
      MODRINTH_PROJECTS: 'beenfo,bluemap,cloth-config,deltalogger,fabric-api,fabric-language-kotlin,fallingtree,lithium,starlight,sodium,unifiedmetrics'
      MODRINTH_ALLOWED_VERSION_TYPE: 'release'
      # PROXY: 'myproxy:3111'
    #tty: true
    #stdin_open: true
    restart: unless-stopped
    depends_on:
      - mcrouter
    ports:
      - '8100' #bluemap
      - '25565'
    volumes:
      - './data/labchicanery-survival/data:/data/:rw'
      - '/home/guest/minecraft/mods/:/mods/:rw'
