version: "3"

services:
  router:
    image: itzg/mc-router:1.16.1@sha256:9fbe6e1877108c69999de7c0ee54837f4d11fbc9b25a4ea9a80741af4fd3202f
    ports:
      - "25565:25565"
    command: --mapping=mc.zah.rocks=proxy:25565,survival.mc.zah.rocks=labchicanery-survival:25565,creative.mc.zah.rocks=labchicanery-creative:25565

  proxy:
    image: itzg/bungeecord:java17@sha256:0182d4938d900f2e6c2778c34fe589f4e976ee22965276d512639f7bb71d94e0
    environment:
      PLUGINS: 'https://download.luckperms.net/1460/velocity/LuckPerms-Velocity-5.4.52.jar,https://github.com/WiIIiam278/HuskChat/releases/download/2.3/HuskChat-2.3.jar'
      JVM_OPTS: '-XX:+UseG1GC -XX:G1HeapRegionSize=4M -XX:+UnlockExperimentalVMOptions -XX:+ParallelRefProcEnabled -XX:+AlwaysPreTouch -XX:MaxInlineLevel=15'
      TYPE: 'VELOCITY'
    ports:
      - '25565'
    volumes:
      - "./data/velocity/:/server/"

  survival:
    image: itzg/minecraft-server:java17-jdk
    environment:
      ONLINE_MODE: 'false'
      UID: 1010
      GID: 1010
      VERSION: '1.19.2'
      TYPE: 'FABRIC'
      EULA: 'TRUE'
      ENABLE_AUTOPAUSE: 'TRUE'
      DIFFICULTY: 'hard'
      MOTD: 'LC - Survival'
      WHITELIST: '65d05271-5ef9-4a49-af14-88079400b83e,fb32208d-815d-45b6-9e82-53830c55bb14,f663c462-3007-4301-9129-882f0ec450a9,319f599f-bd59-42d2-852f-9ac1e67234ca'
      ENFORCE_WHITELIST: 'TRUE'
      #OPS: 'user1,user2'
      OVERRIDE_OPS: 'TRUE'
      ENABLE_RCON: 'TRUE'
      RCON_PASSWORD: '2b65f1d6802eb8b5a513d020959477d92d3ec514b006810ca953fe45978c524d'
      MODE: 'survival'
      PVP: 'FALSE'
      LEVEL: 'labchicanery-survival'
      SERVER_NAME: 'LabChicanery-Survival'
      USE_AIKAR_FLAGS: 'FALSE'
      MEMORY: '8G'
      TZ: 'America/New_York'
      MAX_TICK_TIME: '-1'
      MODS: '/mods'
      # TODO: change to proper seed
      SEED: '1278040446' # 425,-600
      # phosphor instead of starlight
      # textile_backup has to be modified manually for 1.19.2, TODO: remove from ./mods/ at some point
      MODRINTH_PROJECTS: 'beenfo,bluemap,cloth-config,deltalogger,fabric-api,fabric-language-kotlin,fabricproxy-lite,fallingtree,lithium,luckperms,starlight,sodium,unifiedmetrics'
      MODRINTH_ALLOWED_VERSION_TYPE: 'release'
      # PROXY: 'myproxy:3111'
    #tty: true
    #stdin_open: true
    restart: unless-stopped
    depends_on:
      - mcrouter
    ports:
      - '8100' #bluemap
      - '25565'
    volumes:
      - './data/labchicanery-survival/data:/data/:rw'
      - '/home/guest/minecraft/mods/:/mods/:rw'

  creative:
    image: itzg/minecraft-server:java17-jdk
    environment:
      ONLINE_MODE: 'false'
      UID: 1010
      GID: 1010
      VERSION: '1.19.2'
      TYPE: 'FABRIC'
      EULA: 'TRUE'
      ENABLE_AUTOPAUSE: 'TRUE'
      DIFFICULTY: 'peaceful'
      MOTD: 'LC - Creative'
      WHITELIST: '65d05271-5ef9-4a49-af14-88079400b83e,fb32208d-815d-45b6-9e82-53830c55bb14,f663c462-3007-4301-9129-882f0ec450a9,319f599f-bd59-42d2-852f-9ac1e67234ca'
      ENFORCE_WHITELIST: 'TRUE'
      #OPS: 'user1,user2'
      OVERRIDE_OPS: 'TRUE'
      ENABLE_RCON: 'TRUE'
      RCON_PASSWORD: '2b65f1d6802eb8b5a513d020959477d92d3ec514b006810ca953fe45978c524d'
      MODE: 'creative'
      PVP: 'FALSE'
      LEVEL: 'labchicanery-creative'
      SERVER_NAME: 'LabChicanery-Creative'
      USE_AIKAR_FLAGS: 'FALSE'
      MEMORY: '2G'
      TZ: 'America/New_York'
      MAX_TICK_TIME: '-1'
      MODS: '/mods'
      MODRINTH_PROJECTS: 'luckperms,bluemap,cloth-config,deltalogger,fabric-api,fabric-language-kotlin,fabricproxy-lite,lithium,starlight,sodium,unifiedmetrics'
      MODRINTH_ALLOWED_VERSION_TYPE: 'release'
    restart: unless-stopped
    depends_on:
      - mcrouter
    ports:
      - '8100' #bluemap
      - '25565'
    volumes:
      - './data/labchicanery-creative/data:/data/:rw'
      - '/home/guest/minecraft/mods-creative/:/mods/:rw'
