---
- name: ensure gpg is installed
  become: 'yes'
  apt:
    name:
      - gpg
    state: present
    update_cache: yes

- name: add influxdb gpg key
  become: 'yes'
  get_url:
    url: 'https://repos.influxdata.com/influxdb.key'
    dest: '/etc/apt/trusted.gpg.d/influxdb.asc'
    checksum: 'sha256:23a1c8836f0afc5ed24e0486339d7cc8f6790b83886c4c96995b88a061c5bb5d'

- name: add influxdb repository
  become: 'yes'
  apt_repository:
    repo: "{{ influxdb_repository }}"
    state: present
    update_cache: true

- name: ensure telegraf is installed
  become: yes
  apt:
    name:
      - telegraf
    state: present
    update_cache: yes

- name: install telegraf config
  become: 'yes'
  template:
    src: 'telegraf.conf.j2'
    dest: '/etc/telegraf/telegraf.conf'
    mode: 'u=rw'

- name: ensure services are started
  become: yes
  service:
    name: telegraf
    state: started
