version: '3.7'

services:
  memcached:
    hostname: memcached
    image: memcached:alpine3.16@sha256:a6a67c90a8ed59d783ffe08e92ae64a31234cd8419f7e833390df717f576ecdb
    ports:
      - "11211"
    restart: unless-stopped
