version: '3.7'

services:
  thelounge:
    image: linuxserver/thelounge:version-4.2.0
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - "/mnt/data/thelounge/config/:/config/:rw"
    ports:
      - "9000"
    restart: unless-stopped
    depends_on:
      - eas
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.thelounge.rule=Host(`irc.zah.rocks`)"
      - "traefik.http.routers.thelounge.entrypoints=websecure"
      - 'traefik.http.routers.thelounge.middlewares=eas-default'
      - "traefik.http.routers.thelounge.tls.certresolver=myresolver"
