---

- name: ensure enterprise apt list is not present
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/pve-enterprise.list
    state: absent

- name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: do an apt update
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/pve-enterprise.list
    state: absent

- name: Remove dependencies that are no longer required
  ansible.builtin.apt:
    autoremove: yes

- name: ensure packages are installed
  ansible.builtin.apt:
    name:
      - 'neovim'
      - 'ntp'
      - 'python3'
      - 'python3-pip'
      - 'vim'
    state: 'latest'
    update_cache: 'yes'
  when: ansible_distribution == "Debian"

- name: install python packages for managing docker
  ansible.builtin.pip:
    name:
      - 'proxmoxer'
    state: 'latest'

##########################
### labchicanery games ###
##########################

#- name: configure 103 lxc
#  ansible.builtin.include_tasks: configure_103_lxc.yml

##############################
### palmettotech.dev zulip ###
##############################

- name: configure 104 lxc
  ansible.builtin.include_tasks: configure_104_lxc.yml

###################
### START NODES ###
###################

- name: ensure games LXC is started
  community.general.proxmox:
    node: 'eagle'
    api_user: 'root@pam'
    api_password: '{{ pass_root_proxmox }}'
    api_host: '127.0.0.1'
    vmid: 103
    state: 'started'

- name: ensure palmettotech.dev LXC is started
  community.general.proxmox:
    node: 'eagle'
    api_user: 'root@pam'
    api_password: '{{ pass_root_proxmox }}'
    api_host: '127.0.0.1'
    vmid: 104
    state: 'started'

- name: sleep for 5 seconds
  ansible.builtin.wait_for:
    timeout: 5

- name: setup 'ansible' user in nodes
  ansible.builtin.include_tasks: user-setup.yml
