---

- name: add ansible group with gid 2000
  command:
    pct exec {{ item.name }} -- groupadd -g 2000 ansible
  ignore_errors: 'yes'
  with_items:
    - "{{ nodes }}"

- name: add 'ansible' user with uid 2000
  command:
    pct exec {{ item.name }} -- useradd -s /usr/bin/bash -d /home/ansible -g 2000 --create-home -u 2000 ansible 
  ignore_errors: 'yes'
  with_items:
    - "{{ nodes }}"

- name: set 'ansible' user password
  ansible.builtin.shell:
    pct exec {{ item.name }} -- bash -c 'echo ansible:{{ item.pass_ansible }} | chpasswd'
  with_items:
    - "{{ nodes }}"

- name: ensure 'ansible' .ssh dir exists
  command:
    pct exec {{ item.name }} -- mkdir -p /home/ansible/.ssh
  with_items:
    - "{{ nodes }}"

- name: chmod .ssh dir to 0700
  command:
    pct exec {{ item.name }} -- chmod 0700 /home/ansible/.ssh
  with_items:
    - "{{ nodes }}"

- name: create 'ansible' authorized_keys file
  ansible.builtin.shell:
    pct exec {{ item.name }} -- bash -c 'echo {{ ssh_pubkey_ansible }} | tee /home/ansible/.ssh/authorized_keys'
  with_items:
    - "{{ nodes }}"

- name: chmod authorized_keys file to 0600
  ansible.builtin.command:
    pct exec {{ item.name }} -- chmod 0600 /home/ansible/.ssh/authorized_keys
  with_items:
    - "{{ nodes }}"

- name: chown 'ansible's .ssh dir
  command:
    pct exec {{ item.name }} -- chown -R ansible:ansible /home/ansible/.ssh
  with_items:
    - "{{ nodes }}"

#- name: apt update
#  command:
#    pct exec {{ item.name }} -- apt update
#  with_items:
#    - "{{ nodes }}"

- name: dnf update
  command:
    pct exec {{ item.name }} -- dnf update -y
  with_items:
    - "{{ nodes }}"

#- name: apt install sudo
#  command:
#    pct exec {{ item.name }} -- apt install sudo -y
#  with_items:
#    - "{{ nodes }}"

- name: dnf install sudo, openssh-server
  command:
    pct exec {{ item.name }} -- dnf install -y sudo openssh-server
  with_items:
    - "{{ nodes }}"

- name: add 'ansible' to 'sudoers'
  command:
    pct exec {{ item.name }} -- usermod -aG wheel ansible
  with_items:
    - "{{ nodes }}"

- name: add 'ansible' to 'sudoers'
  command:
    pct exec {{ item.name }} -- systemctl enable --now sshd
  with_items:
    - "{{ nodes }}"
