velocity_motd: 'Lab Shenanigans'
velocity_port: 25565
velocity_query_port: 25549
velocity_metrics_id: '{{ vault_velocity_metrics_id }}'

survival_server_port: 25450
survival_query_port: 25550
survival_rcon_port: 25750
survival_rcon_pass: '{{ vault_survival_rcon_pass }}'

creative_server_port: 25451
creative_query_port: 25551
creative_rcon_port: 25751
creative_rcon_pass: '{{ vault_creative_rcon_pass }}'

influx_url: 'https://influxdb.metrics.andrewzah.com' 
influx_bucket: 'unifiedmetrics-neptunemc'
influx_organization: 'andrewzah'

proxy_influx_token: '{{ vault_proxy_influx_token }}'

velocity_forwarding_secret: '{{ vault_velocity_forwarding_secret }}'

ssh_keys: '{{ vault_ssh_keys }}'
