version: '3.7'

services:
  vaultwarden:
    # 2022-09-25
    image: vaultwarden/server:1.25.2-alpine@sha256:7011d4216a00fcd79785b8b31d61b897e05d959aa37681323dd9c0155655bbbc
    environment:
      WEBSOCKET_ENABLED: 'true'
      SIGNUPS_ALLOWED: 'false'
      LOG_FILE: '/data/bitwarden.log'
    ports:
      - "80"
      - "3012"
    volumes:
      - "./data/bitwarden-rs/:/data/:rw"
    restart: unless-stopped
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bitwarden-ui.rule=Host(`bit.zah.rocks`)"
      - "traefik.http.routers.bitwarden-ui.entrypoints=websecure"
      - "traefik.http.routers.bitwarden-ui.tls.certresolver=myresolver"
      - "traefik.http.routers.bitwarden-ui.service=bitwarden-ui"
      - "traefik.http.services.bitwarden-ui.loadbalancer.server.port=80"

      - "traefik.http.routers.bitwarden-wss.rule=Host(`bit.zah.rocks`) && Path(`/notifications/hub`)"
      - "traefik.http.routers.bitwarden-wss.tls.certresolver=myresolver"
      - "traefik.http.routers.bitwarden-wss.entrypoints=websecure"
      - "traefik.http.routers.bitwarden-wss.service=bitwarden-wss"
      - "traefik.http.services.bitwarden-wss.loadbalancer.server.port=3012"
