---

services:
  vaultwarden:
    # 2024-10-02
    image: vaultwarden/server:1.32.0-alpine@sha256:e3efdc8a9961643f5f0d2c72596aedfe4b4fcfce9836e18c1e8ba0b8c2e06459
    environment:
      DOMAIN: 'https://bit.zah.rocks'
      WEBSOCKET_ENABLED: 'true'
      SIGNUPS_ALLOWED: 'false'
      LOG_FILE: '/data/bitwarden.log'
    env_file:
      - "~/docker/services/vaultwarden/secret.env"
    ports:
      - "80"
      - "3012"
    volumes:
      - "~/docker/data/bitwarden-rs/:/data/:rw"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vaultwarden-ui.rule=Host(`bit.zah.rocks`)"
      - "traefik.http.routers.vaultwarden-ui.entrypoints=websecure"
      - "traefik.http.routers.vaultwarden-ui.tls.certresolver=myresolver"
      - "traefik.http.routers.vaultwarden-ui.service=vaultwarden-ui"
      - "traefik.http.services.vaultwarden-ui.loadbalancer.server.port=80"
      # websockets
      - "traefik.http.routers.vaultwarden-wss.rule=Host(`bit.zah.rocks`) && Path(`/notifications/hub`)"
      - "traefik.http.routers.vaultwarden-wss.tls.certresolver=myresolver"
      - "traefik.http.routers.vaultwarden-wss.entrypoints=websecure"
      - "traefik.http.routers.vaultwarden-wss.service=vaultwarden-wss"
      - "traefik.http.services.vaultwarden-wss.loadbalancer.server.port=3012"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 5s
