---

services:
  atuin:
    # 2024-03-16
    image: ghcr.io/atuinsh/atuin:82a7c8d
    ports:
        - "8888"
    command: server start
    environment:
      RUST_LOG: 'info'
    env_file:
      "~/docker/services/atuin/secret.env"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.atuin.rule=Host(`atuin.zah.rocks`)"
      - "traefik.http.routers.atuin.entrypoints=websecure"
      - "traefik.http.routers.atuin.tls.certresolver=myresolver"

