---

#- name: ensure packages are installed
#  ansible.builtin.apt:
#    name:
#      - 'openssh-client'
#      - 'openssh-server'
#    state: 'present'
#    update_cache: 'yes'

# TODO: optimize
- name: ensure packages are NOT installed
  ansible.builtin.apt:
    name:
      - 'nano'
      - 'sendmail'
    state: 'absent'
    update_cache: 'yes'
