version: '3.7'

services:
  papermerge:
    image: linuxserver/papermerge:version-v1.5.0
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - "${COMPOSE_ROOT}/data/papermerge/config/:/config/:rw"
      - "${COMPOSE_ROOT}/data/papermerge/data/:/data/:rw"
    ports:
      - "8000"
    restart: unless-stopped
    depends_on:
      - eas
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.papermerge.rule=Host(`ds.zah.rocks`)"
      - "traefik.http.routers.papermerge.entrypoints=websecure"
      - 'traefik.http.routers.papermerge.middlewares=eas-default'
      - "traefik.http.routers.papermerge.tls.certresolver=myresolver"
