version: '3.7'

services:
  firefly:
    image: jc5x/firefly-iii:version-5.4.5
    environment:
      APP_URL: 'https://z.zah.rocks'
      TZ: 'America/New_York'
      TRUSTED_PROXIES: '**'
      DB_HOST: 'postgres'
      DB_PORT: 5432
      DB_CONNECTION: 'pgsql'
      DB_DATABASE: 'firefly'
      DB_USERNAME: 'firefly'
    env_file:
      - "/mnt/data/services/firefly/secret.env"
    volumes:
      - "/mnt/data/firefly:/var/www/html/storage/upload:rw"
    ports:
      - "8080"
    restart: unless-stopped
    depends_on:
      - eas
      - postgres
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.firefly.rule=Host(`z.zah.rocks`)"
      - "traefik.http.routers.firefly.entrypoints=websecure"
      - 'traefik.http.routers.firefly.middlewares=eas-default'
      - "traefik.http.routers.firefly.tls.certresolver=myresolver"

