version: '3.7'

services:
  syncthing:
    # 2023-04-02
    image: lscr.io/linuxserver/syncthing:1.23.2@sha256:56585a380a6ceb142f2605803b451a98665cc93dc4f7b4ba0fe8bb08b6e2a36c
    environment:
      PUID: 1000
      PGID: 1000
      TZ: 'America/New_York'
    volumes:
      - "~/docker/data/syncthing/config/:/config/:rw"
      - "/mnt/eagle/data/syncthing/:/data/syncthing/:rw"
    restart: unless-stopped
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.syncthing.rule=Host(`syncthing.zah.rocks`)"
      - "traefik.http.routers.syncthing.entrypoints=websecure"
      - "traefik.http.routers.syncthing.tls.certresolver=myresolver"
