---

services:
  syncthing:
    # 2024-10-02
    image: linuxserver/syncthing:1.27.12@sha256:0141ef2c1ad754d6c93b92c0aa71648bf8c08b97ed80bf943091ad24332fcbb5
    environment:
      PUID: 1000
      PGID: 1000
      TZ: 'America/New_York'
    volumes:
      - "~/docker/data/syncthing/config/:/config/:rw"
      - "/mnt/eagle/data/syncthing/:/data/syncthing/:rw"
    restart: unless-stopped
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.syncthing.rule=Host(`syncthing.zah.rocks`)"
      - "traefik.http.routers.syncthing.entrypoints=websecure"
      - "traefik.http.routers.syncthing.tls.certresolver=myresolver"
