services:
  goatcounter:
    image: docker.io/andrewzah/goatcounter:v2.4.1
    environment:
      GC_PORT: "3443"
      GC_LISTEN: "0.0.0.0:3443"
      GC_TLS: "none"
      GC_ERRORS: "mailto:zah@andrewzah.com"
      GC_EMAIL_FROM: "goatcounter@zah.rocks"
    env_file:
      - "~/docker/services/goatcounter/secret.env"
    volumes:
      - "~/docker/data/goatcounter/:/data/"
    ports:
      - "3443"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.goatcounter.rule=Host(`stats.benzah.com`) || Host(`stats.andrewzah.com`) || Host(`stats.homegrownbinaries.com`) || Host(`stats.worldwarrior.online`)"
      - "traefik.http.routers.goatcounter.entrypoints=websecure"
      - "traefik.http.routers.goatcounter.tls.certresolver=myresolver"
