---

services:
  # 2024-11-11
  goatcounter:
    image: docker.io/andrewzah/goatcounter:530ab5edff553923fb04d9e1b1a9771f8a6d0461@sha256:2dbb366e754dbdbc039a6b49e264fe9222f243d24a402b418c36dfdb49f4a8a5
    environment:
      GC_PORT: "3443"
      GC_LISTEN: "0.0.0.0:3443"
      GC_TLS: "none"
      GC_ERRORS: "mailto:zah@andrewzah.com"
      GC_EMAIL_FROM: "goatcounter@zah.rocks"
    env_file:
      - "~/docker/services/goatcounter/secret.env"
    volumes:
      - "~/docker/data/goatcounter/:/data/"
    ports:
      - "3443"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      ## dns-challenge
      - "traefik.http.routers.goatcounter-dns.rule=Host(`stats.andrewzah.com`) || Host(`stats.worldwarrior.online`)"
      - "traefik.http.routers.goatcounter-dns.entrypoints=websecure"
      - "traefik.http.routers.goatcounter-dns.tls.certresolver=cloudflare"
      ## tls-challenge
      - "traefik.http.routers.goatcounter-tls.rule=Host(`stats.benzah.com`) || Host(`stats.homegrownbinaries.com`)"
      - "traefik.http.routers.goatcounter-tls.entrypoints=websecure"
      - "traefik.http.routers.goatcounter-tls.tls.certresolver=myresolver"
