version: '3.7'

services:
  lam:
    image: ldapaccountmanager/lam:stable
    env_file:
      - "/mnt/data/services/openldap/secret.env"
    hostname: lam.idp.zah.rocks
    environment:
      LAM_SKIP_PRECONFIGURE: 'false'
      LDAP_DOMAIN: 'zah.rocks'
      LDAP_SERVER: 'ldap://openldap:389'
      LDAP_BASE_DN: 'dc=zah,dc=rocks'
      LDAP_USERS_DN: 'ou=people,dc=zah,dc=rocks'
      LDAP_GROUPS_DN: 'ou=groups,dc=zah,dc=rocks'
      ADMIN_USER: 'cn=admin,dc=zah,dc=rocks'
      LAM_LANG: 'en_US'
    ports:
      - "80"
    depends_on:
      - traefik
    volumes:
      - "/mnt/data/lam/etc/:/etc/ldap-account-manager/"
      - "/mnt/data/lam/var/config/:/var/lib/ldap-account-manager/config"
      - "/mnt/data/lam/var/sess/:/var/lib/ldap-account-manager/sess"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lam.rule=Host(`lam.idp.zah.rocks`)"
      - "traefik.http.routers.lam.entrypoints=websecure"
      - "traefik.http.routers.lam.tls.certresolver=myresolver"

  openldap:
    image: osixia/openldap:1.4.0
    env_file:
      - "/mnt/data/services/openldap/secret.env"
    environment:
      LDAP_DOMAIN: 'zah.rocks'
      LDAP_ORGANISATION: 'Zah'
      LDAP_BASE_DN: 'dc=zah,dc=rocks'
      LDAP_TLS: 'false'
    volumes:
      - "/mnt/data/openldap/openldap/:/etc/ldap/slapd.d/"
      - "/mnt/data/openldap/runtime/:/var/lib/ldap"
    restart: unless-stopped
