---

services:
  online-worldwarrior:
    # 2024-06-26
    image: docker.io/andrewzah/online.worldwarrior:latest@sha256:ca6c74d2889c403eed273ae43706c2224567114dbae39270e9ac53f365462c10
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.andrewzahcom.rule=Host(`worldwarrior.online`)"
      - "traefik.http.routers.andrewzahcom.entrypoints=websecure"
      - "traefik.http.routers.andrewzahcom.tls.certresolver=myresolver"
