---

services:
  online-worldwarrior:
    # 2024-10-02
    image: docker.io/andrewzah/online.worldwarrior:0.7.5@sha256:0827108f2d7c2f545dbca1448ea05202d7186b665707eb49e6bfc00c72ce516f
    restart: unless-stopped
    ports:
      - "2020"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.online-worldwarrior.rule=Host(`worldwarrior.online`)"
      - "traefik.http.routers.online-worldwarrior.entrypoints=websecure"
      - "traefik.http.routers.online-worldwarrior.tls.certresolver=cloudflare"
