---

services:
  online-worldwarrior:
    # 2024-07-05
    image: docker.io/andrewzah/online.worldwarrior:0.7.5@sha256:9a83105d10c10fa1921660d09662edd63c0df4b448dd323540801f6b218c2864
    restart: unless-stopped
    ports:
      - "2020"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.online-worldwarrior.rule=Host(`worldwarrior.online`)"
      - "traefik.http.routers.online-worldwarrior.entrypoints=websecure"
      - "traefik.http.routers.online-worldwarrior.tls.certresolver=myresolver"
