version: '3.7'

services:
  healthchecks:
    # 2022-10-03
    image: linuxserver/healthchecks:2.3.20220923@sha256:26fd993fab991780a36a9b9bc34d9f21e9c3804aaabc70e2fc524e7e2dc99a27
    environment:
      SITE_ROOT: "healthchecks.zah.rocks"
      SITE_NAME: "Zah HealthChecks"
      EMAIL_HOST: "smtp-relay.sendinblue.com"
      EMAIL_PORT: 587
      EMAIL_HOST_USER: "zah@andrewzah.com"
      EMAIL_USE_TLS: "True"
      ALLOWED_HOSTS: "['127.0.0.1', 'localhost', 'healthchecks.zah.rocks']"
      CSRF_TRUSTED_ORIGINS: "['https://healthchecks.zah.rocks']"
      DEFAULT_FROM_EMAIL: 'Zah Healthchecks <zah@andrewzah.com>'
      SUPERUSER_EMAIL: "zah@andrewzah.com"
      REGENERATE_SETTINGS: "True"
      UWSGI_BUFFER_SIZE: 65535
    env_file:
      - "~/docker/services/healthchecks/secret.env"
    ports:
      - "8000"
    volumes:
      - "~/docker/data/healthchecks/config/:/config/"
    restart: unless-stopped
    depends_on:
      - traefik
      - eas
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.healthchecks.rule=Host(`healthchecks.zah.rocks`)"
      - "traefik.http.routers.healthchecks.entrypoints=websecure"
      - "traefik.http.routers.healthchecks.tls.certresolver=myresolver"
