---

services:
  healthchecks:
    # 2024-10-02
    image: ghcr.io/linuxserver/healthchecks:3.6.20240930
    environment:
      TZ: 'Asia/Seoul'
      PUID: 1000
      PGID: 1000
      SITE_ROOT: "https://healthchecks.zah.rocks"
      SITE_NAME: "Zah Healthchecks"
      ALLOWED_HOSTS: 'healthchecks.zah.rocks'
      REGENERATE_SETTINGS: 'True'
      COMPRESS_ENABLED: 'True'
      DEBUG: 'False'
    env_file:
      - "~/docker/services/healthchecks/secret.env"
    ports:
      - "8000"
    volumes:
      - "~/docker/data/healthchecks/config/:/config/"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.healthchecks.rule=Host(`healthchecks.zah.rocks`)"
      - "traefik.http.routers.healthchecks.entrypoints=websecure"
      - "traefik.http.routers.healthchecks.tls.certresolver=myresolver"
      #- 'traefik.http.routers.healthchecks.middlewares=eas-healthchecks'
      #- "traefik.http.middlewares.eas-healthchecks.forwardauth.trustForwardHeader=true"
      #- "traefik.http.middlewares.eas-healthchecks.forwardauth.authResponseHeaders=X-Userinfo, X-Id-Token, X-Access-Token, Authorization"
