version: '3.7'

services:
  healthchecks:
    # 2023-03-11
    image: 'ghcr.io/linuxserver/healthchecks:2.7.20230306@sha256:ab7023e81525473003c80e7803dba111a6bb734273cc1d14c3ef2672e86a0a07'
    environment:
      PUID: 1000
      PGID: 1000
      SITE_ROOT: "https://healthchecks.zah.rocks"
      SITE_NAME: "Zah Healthchecks <zah@andrewzah.com>"
      ALLOWED_HOSTS: "['healthchecks.zah.rocks']"
      REGENERATE_SETTINGS: "True"
      UWSGI_BUFFER_SIZE: 65535
      COMPRESS_ENABLED: 'True'
      DEBUG: 'False'
    env_file:
      - "~/docker/services/healthchecks/secret.env"
    ports:
      - "8000"
    volumes:
      - "~/docker/data/healthchecks/config/:/config/"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.healthchecks.rule=Host(`healthchecks.zah.rocks`)"
      - "traefik.http.routers.healthchecks.entrypoints=websecure"
      #- 'traefik.http.routers.healthchecks.middlewares=eas-healthchecks'
      - "traefik.http.routers.healthchecks.tls.certresolver=myresolver"
      #- "traefik.http.middlewares.eas-healthchecks.forwardauth.trustForwardHeader=true"
      #- "traefik.http.middlewares.eas-healthchecks.forwardauth.authResponseHeaders=X-Userinfo, X-Id-Token, X-Access-Token, Authorization"
