services:
  com-homegrownbinaries:
    # 2024-03-03
    image: docker.io/andrewzah/homegrownbinaries:latest
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homegrownbinariescom.rule=Host(`homegrownbinaries.com`)"
      - "traefik.http.routers.homegrownbinariescom.entrypoints=websecure"
      - "traefik.http.routers.homegrownbinariescom.tls.certresolver=myresolver"
