services:
  com-andrewzah:
    # 2023-06-13
    image: docker.io/andrewzah/homegrownbinaries:latest
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.andrewzahcom.rule=Host(`homegrownbinaries.com`)"
      - "traefik.http.routers.andrewzahcom.entrypoints=websecure"
      - "traefik.http.routers.andrewzahcom.tls.certresolver=myresolver"
