version: '3.7'

services:
  redis:
    image: redis:6.0.9-alpine3.12
    command: 'redis-server /redis.conf'
    ports:
      - "6379"
      - "36379:6379"
    volumes:
      - "/mnt/data/services/redis/redis.conf:/redis.conf"
      - "/mnt/data/redis/data:/data"
    restart: unless-stopped
