---

services:
  navidrome:
    # 2024-07-10
    image: docker.io/deluan/navidrome:pr-2709@sha256:4e5846c25eef2d38f4ccf43cd51541e75a034a339300250cd2ac7c6142d64932
    environment:
      ND_PORT: 4533
      ND_MUSICFOLDER: '/music'
      ND_DATAFOLDER: '/data'
      ND_SCANSCHEDULE: '@every 24h'
      ND_COVERJPEGQUALITY: 85
      ND_TRANSCODINGCACHESIZE: "500MB"
      ND_LOGLEVEL: 'info'
      ND_ENABLEDOWNLOADS: 'true'
      ND_DEVACTIVITYPANEL: 'false'
      ND_AUTOIMPORTPLAYLISTS: 'false'
      ND_ENABLECOVERANIMATION: 'false'
      ND_LISTENBRAINZ_ENABLED: 'false'
      ND_ENABLEGRAVATAR: 'false'
      ND_ENABLESTARRATING: 'false'
      ND_LASTFM_ENABLED: 'false'
      ND_DEFAULTLANGUAGE: 'en'
      ND_PROMETHEUS_ENABLED: 'true'
      ND_ENABLETRANSCODINGCONFIG: 'false'
      ND_MAXSIDEBARPLAYLISTS: 7
    ports:
      - "4533"
    volumes:
      - "~/docker/data/navidrome:/data"
      - "/mnt/eagle/media/music:/music"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.navidrome.rule=Host(`music.zah.rocks`)"
      - "traefik.http.routers.navidrome.entrypoints=websecure"
      - "traefik.http.routers.navidrome.tls.certresolver=myresolver"

