version: '3.7'

services:
  navidrome:
    # 2022-11-07
    image: deluan/navidrome@sha256:a1732c8b50760713fea48ca9b949fb7bd1a75c2891363f468c38903a26606f4c
    environment:
      ND_PORT: 4533
      ND_MUSICFOLDER: '/music'
      ND_DATAFOLDER: '/data'
      ND_SCANSCHEDULE: '@every 1m'
      ND_COVERJPEGQUALITY: 85
      ND_TRANSCODINGCACHESIZE: "500MB"
      ND_LOGLEVEL: 'info'
      # enable things we want
      ND_ENABLEDOWNLOADS: 'true'
      # disable for performance fix
      ND_DEVACTIVITYPANEL: 'false'
      # TODO: spotify
      #ND_SPOTIFY_ID:
      #ND_SPOTIFY_SECRET:
      # disable things we don't need / want
      ND_AUTOIMPORTPLAYLISTS: 'false'
      ND_ENABLEGRAVATAR: 'false'
      ND_ENABLESTARRATING: 'false'
      ND_LASTFM_ENABLED: 'false'
      # disable for security
      ND_ENABLETRANSCODINGCONFIG: 'false'
      ND_PROMETHEUS_ENABLED: 'true'
    ports:
        - "4533"
    volumes:
      - "~/docker/data/navidrome:/data"
      - "/mnt/eagle/media/music:/music"
    restart: unless-stopped
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.navidrome.rule=Host(`music.zah.rocks`)"
      - "traefik.http.routers.navidrome.entrypoints=websecure"
      - "traefik.http.routers.navidrome.tls.certresolver=myresolver"

