---
x-immich-common: &immich-common
  # 2024-02-28
  image: ghcr.io/immich-app/immich-server:v1.97.0
  environment:
    UPLOAD_LOCATION: '/data'
    TZ: 'America/New_York'
  env_file:
    - "~/docker/services/immich/secret.env"
  volumes:
    - "~/docker/data/immich/data/:/data/:rw"
  restart: unless-stopped

services:
  immich:
    command: ["start.sh", "immich"]
    <<: *immich-common
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.photos.rule=Host(`photos.zah.rocks`)"
      - "traefik.http.routers.photos.entrypoints=websecure"
      - 'traefik.http.routers.photos.middlewares=eas-default'
      - "traefik.http.routers.photos.tls.certresolver=myresolver"

  immich-microservices:
    command: ["start.sh", "microservices"]
    depends_on:
      - immich
    <<: *immich-common

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:v1.97.0
    ports:
      - "3003"
    volumes:
      - "~/docker/data/immich/ml-cache/:/cache/:rw"
