version: '3.7'

services:
  eas:
    # 2022-10-02
    image: 'travisghansen/external-auth-server:v0.12.4@sha256:a2651eba831dbeaf2c720e5df52f215f3d7b03c2e3e114c9d1ae02c8a8ab887f'
    env_file:
      - "~/docker/services/external-auth-server/secret.env"
    environment:
      EAS_PORT: 8080
      EAS_CONFIG_TOKEN_STORES: '{}'
      EAS_LOG_LEVEL: "info"
      EAS_ALLOW_EVAL: 'true'
      EAS_STORE_OPTS: '{"store":"redis","host":"redis"}'
    ports:
      - "8080"
    restart: unless-stopped
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.eas.rule=Host(`eas.zah.rocks`)"
      - "traefik.http.routers.eas.entrypoints=websecure"
      - "traefik.http.routers.eas.tls.certresolver=myresolver"

      - "traefik.http.middlewares.eas-default.forwardauth.trustForwardHeader=true"
      - "traefik.http.middlewares.eas-default.forwardauth.authResponseHeaders=X-Userinfo, X-Id-Token, X-Access-Token, Authorization"
      - "traefik.http.middlewares.eas-default.forwardauth.address=https://eas.zah.rocks/verify?config_token=3nSlRC4QprqbS1H3wyfq1jKs1ftDRb2%2B%2BlPZhEaxYsq1s9NRDf%2FbVXuTeRZrL6KTqkvPuzc1CMzI9BvAlE%2FmdXNucYSR%2FAVmbxXmeoAuMX4IXqIwdJCylhUNuKd4q2uyC%2FNfJyLVDILvaKjAu7VE8unvJ%2FQGN4%2BgIzNMlH%2BOQ24Wr5TMfT90oF%2BWPP86Ax45g5JFkc8uJWYg6ROpnQoJyWglJIgtVJtiiPPbfa%2FiGZw%2Bv1qx0CSUAOOCGIokZ6toAgJTEe5btZF8vPU7RBMzgayRkXW3b5omZtmTcNX91GQEYPk2yj%2FWDg9gqsfgF6WwefNclqPNniD6llsDWpaKh%2FUofSLEuZxMHAdMgp3C4Iu2EpGB81Cbh9a3CdO5uzrYQMOiyxB5cCvCK6VaWHEAXEpPGdhlC2L9Uga4Iin3kkpPKaVTbOXkjiAiNSssr%2B%2F%2F%2FnKVEPKNyEHPufRzojbi45VdY2jzt7KN%2BgzmmBERETFBzeBQpQyhGqklaShhZCuwx7Lr6LI0fIs3vcvpR%2BHK2bL0UgaWi9Gr9YCNPa%2BQkLp1AaL38kHy4UwVI54r3H11RUMlzIg1YrUyj0NF9nNQiQyRSlEDvW4udwX0gYRnO4xTMq9dHyK9tfO3KFWTauTFiTjjDdHsRFZm92GETP5aWNl%2BB6UZHO01wjiMdLMBa8Xt4ViphUmKTAVyez6oHB9HRqGghRHM%2BON0oIPdfZPudUEi9FqbqYBlGCD2KQgA9ot0%2BvXdZO1Amh9jiMsSNE0SrANU0OBwFjNMNqMSsdjbupWukpVUgsHfUGx1NYgJcO1YLE8p95YWox1yzjDwCmzEXEsocANgmrf1DCyN5zAkyKP9NuCjQkfMNp%2Fn961%2B%2FD2CCKpO5RzcKohGbWXXD0okHoS%2FAfVT2styB9jUJUKrXRJTTWWGv9hbUS90MG6Ed3LGWBKZctSTPNpbZrk%2FwfU4ITmxWctwJS5Ak4Ajx%2B9r%2Bu6zOnJnwJ9aGcykXwyA9Xt2W2V6CP1ocmeXJ3L1BqdWY%2FEp6yCSqmDJ8wGmJLDBbHDG7zyoU5cbGrWmBrbnSHyBOC%2F7K99swVEz1xScJlXykirWyZye1AGEK7C7LcOIgVLtDu0ONqpn2y4jhZjvurDhxTXLHRsbsdSkFvCPM%2BhzOs6Vrb8MrZFX1GcYC47Y1FGhUDK9bxTq%2F8tHvf%2B7v7nwzRjBK55G68NxAPYpqTSU8mGx7fDFclfw%2FH7x4nTgyle0BDFEcHHLLRK0yzCNdty2PMHyfhgV70YXapeqiApwThysRXfBEhEXQmzRAzGua4dLWb9wOD0Oa%2Fv%2B%2F1BHwyiqeSx6jyT%2BAwHprdWRsWXf9JDfyGISDozQZ72gaiF9Xg%3D%3D"

# vim: set syntax=none #
