---

services:
  traefik:
    # 2022-09-25
    image: traefik:v2.8.7@sha256:ad7914fcb229ba6569223535ca6574eda78f1eff237a20df2ba744f893cfeaef
    hostname: 'traefik'
    restart: 'unless-stopped'
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file=true"
      - "--providers.file.watch=true"
      - "--providers.file.filename=/etc/traefik/rules.toml"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.ssh.address=:22"
      #- "--entrypoints.hkps.address=:11371"
      - "--entryPoints.web.forwardedHeaders.insecure"
      - "--entryPoints.websecure.forwardedHeaders.insecure"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=admin@andrewzah.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https@docker"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redir.redirectScheme.scheme=https"

        #- "traefik.http.routers.bluemap.rule=Host(`fabric.genessee.zah.rocks`)"
        #- "traefik.http.routers.bluemap.entrypoints=websecure"
        #- "traefik.http.routers.bluemap.tls.certresolver=myresolver"
        #- "traefik.http.services.bluemap.loadbalancer.server.url=http://192.168.1.16"
        #- "traefik.http.services.bluemap.loadbalancer.server.port=8100"
    ports:
      - "22:22"
      - "80:80"
      - "443:443"
      - "8080:8080"
      - "11371:11371"
    volumes:
      - "~/docker/services/traefik/rules.toml:/etc/traefik/rules.toml"
      - "~/docker/data/traefik/letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    #extra_hosts:
    #  - host.docker.internal:172.18.0.1
    #  - host.docker.internal2:192.168.1.1
