[http.routers]
  [http.routers.palmettotech-zulip]
    entrypoints = [ "websecure" ]
    rule = "Host(`zulip.palmettotech.dev`)"
    service = "palmettotech-zulip"
    [http.routers.palmettotech-zulip.tls]
      certResolver = "myresolver"

  [http.routers.bluemap-survival]
    entrypoints = [ "websecure" ]
    rule = "Host(`survival-map.mc.zah.rocks`)"
    service = "bluemap-survival"
    [http.routers.bluemap.tls]
      certResolver = "myresolver"

  [http.routers.bluemap-creative]
    entrypoints = [ "websecure" ]
    rule = "Host(`creative-map.mc.zah.rocks`)"
    service = "bluemap-creative"
    [http.routers.bluemap.tls]
      certResolver = "myresolver"

[http.services]
  [http.services.palmettotech-zulip.loadBalancer]
    [[http.services.palmettotech-zulip.loadBalancer.servers]]
      url = "http://192.168.2.31:80"

  [http.services.bluemap-survival.loadBalancer]
    [[http.services.bluemap-survival.loadBalancer.servers]]
      url = "http://192.168.2.29:8100"

  [http.services.bluemap-creative.loadBalancer]
    [[http.services.bluemap-creative.loadBalancer.servers]]
      url = "http://192.168.2.29:8101"
