[http.routers]
  [http.routers.jellyfin]
    entrypoints = [ "websecure" ]
    rule = "Host(`flix.zah.rocks`)"
    service = "jellyfin"
    [http.routers.jellyfin.tls]
      certResolver = "myresolver"

  [http.routers.bluemap-survival]
    entrypoints = [ "websecure" ]
    rule = "Host(`survival-map.mc.zah.rocks`)"
    service = "bluemap-survival"
    [http.routers.bluemap-survival.tls]
      certResolver = "myresolver"

  [http.routers.bluemap-creative]
    entrypoints = [ "websecure" ]
    rule = "Host(`creative-map.mc.zah.rocks`)"
    service = "bluemap-creative"
    [http.routers.bluemap-creative.tls]
      certResolver = "myresolver"

[http.services]
  [http.services.jellyfin.loadBalancer]
    [[http.services.jellyfin.loadBalancer.servers]]
      url = "http://192.168.2.6:8096"

  [http.services.bluemap-survival.loadBalancer]
    [[http.services.bluemap-survival.loadBalancer.servers]]
      url = "http://192.168.2.29:8100"

  [http.services.bluemap-creative.loadBalancer]
    [[http.services.bluemap-creative.loadBalancer.servers]]
      url = "http://192.168.2.29:8101"
