[http.routers]
  [http.routers.ben-website]
    entrypoints = [ "websecure" ]
    rule = "Host(`new.benzah.com`)"
    service = "ben-website"
    [http.routers.ben-website.tls]
      certResolver = "myresolver"

  [http.routers.bluemap]
    entrypoints = [ "websecure" ]
    rule = "Host(`map.fabric.genessee.zah.rocks`)"
    service = "bluemap"
    [http.routers.bluemap.tls]
      certResolver = "myresolver"

  [http.routers.jellyfin]
    entrypoints = [ "websecure" ]
    rule = "Host(`flix.zah.rocks`)"
    service = "jellyfin"
    [http.routers.jellyfin.tls]
      certResolver = "myresolver"

  [http.routers.syncthing]
    entrypoints = [ "websecure" ]
    rule = "Host(`syncthing.zah.rocks`)"
    service = "syncthing"
    [http.routers.syncthing.tls]
      certResolver = "myresolver"

[http.services]
  [http.services.ben-website.loadBalancer]
    [[http.services.ben-website.loadBalancer.servers]]
      url = "http://192.168.1.30:80"

  [http.services.bluemap.loadBalancer]
    [[http.services.bluemap.loadBalancer.servers]]
      url = "http://192.168.1.16:8100"

  [http.services.jellyfin.loadBalancer]
    [[http.services.jellyfin.loadBalancer.servers]]
      url = "http://192.168.1.20:8096"

  [http.services.syncthing.loadBalancer]
    [[http.services.syncthing.loadBalancer.servers]]
      url = "http://192.168.1.9:8384"
