---

services:
  postgres:
    hostname: postgres
    image: docker.io/andrewzah/postgres-custom:2024-03-03@sha256:bcc1a0963ed8757b00d6a20a59b62eabcb856eeed11ea47a1863495076a4959e
    ports:
      - "5432"
      - "5433:5432"
    environment:
      PGDATA: '/var/lib/postgresql/data'
    env_file:
      - "~/docker/services/postgres/secret.env"
    volumes:
      - "~/docker/data/postgres15/:/var/lib/postgresql/data/:rw"
    restart: unless-stopped
