version: '3.7'

services:
  postgres:
    hostname: postgres
    image: postgres:14.5-alpine
    ports:
      - "5432"
      - "5433:5432"
    environment:
      PGDATA: '/var/lib/postgresql/data'
    env_file:
      - "~/docker/services/postgres/secret.env"
    volumes:
      - "~/docker/data/postgres/:/var/lib/postgresql/data/:rw"
    restart: unless-stopped
