version: '3.7'

services:
  postgres:
    image: postgres:12.12-alpine
    ports:
      - "5432"
    environment:
      PGDATA: '/var/lib/postgresql/data'
    env_file:
      - "./secret.env"
    volumes:
      - "./data/postgres/:/var/lib/postgresql/data/:rw"
    restart: unless-stopped
