version: '3.7'

services:
  cryptpad:
    image: promasu/cryptpad:alpine
    environment:
      CPAD_MAIN_DOMAIN: 'cryptpad.zah.rocks'
      CPAD_SANDBOX_DOMAIN: 'sandbox.cryptpad.zah.rocks'
      CPAD_TRUSTED_PROXY: '172.18.0.1'
    ports:
      - "3000"
      - "3001"
    depends_on:
      - eas
      - traefik
    volumes:
      - "${COMPOSE_ROOT}/data/cryptpad/blob:/cryptpad/blob"
      - "${COMPOSE_ROOT}/data/cryptpad/block:/cryptpad/block"
      - "${COMPOSE_ROOT}/data/cryptpad/config:/cryptpad/config"
      - "${COMPOSE_ROOT}/data/cryptpad/customize/:/cryptpad/customize/"
      - "${COMPOSE_ROOT}/data/cryptpad/data/:/cryptpad/data/"
      - "${COMPOSE_ROOT}/data/cryptpad/files/:/cryptpad/datastore/"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cryptpad.rule=Host(`cryptpad.zah.rocks`)"
      - "traefik.http.routers.cryptpad.entrypoints=websecure"
      - 'traefik.http.routers.cryptpad.middlewares=eas-default'
      - "traefik.http.routers.cryptpad.service=cryptpad"
      - "traefik.http.routers.cryptpad.tls.certresolver=myresolver"
      - "traefik.http.services.cryptpad.loadbalancer.server.port=3000"

      - "traefik.http.routers.cryptpad-wss.rule=Host(`cryptpad.zah.rocks`) && Path(`/cryptpad_websocket`)"
      - "traefik.http.routers.cryptpad-wss.tls.certresolver=myresolver"
      - "traefik.http.routers.cryptpad-wss.entrypoints=websecure"
      - "traefik.http.routers.cryptpad-wss.service=cryptpad-wss"
      - "traefik.http.services.cryptpad-wss.loadbalancer.server.port=3000"

      - "traefik.http.routers.cryptpad-sandbox.rule=Host(`sandbox.cryptpad.zah.rocks`)"
      - "traefik.http.routers.cryptpad-sandbox.entrypoints=websecure"
      - 'traefik.http.routers.cryptpad-sandbox.middlewares=eas-default'
      - "traefik.http.routers.cryptpad-sandbox.service=cryptpad-sandbox"
      - "traefik.http.routers.cryptpad-sandbox.tls.certresolver=myresolver"
      - "traefik.http.services.cryptpad-sandbox.loadbalancer.server.port=3001"
