version: '3.7'

services:
  monica:
    # 07-12-08
    image: monica:3-apache
    env_file:
      - "${COMPOSE_ROOT}/services/monica/secret.env"
    environment:
      APP_DISABLE_SIGNUP: 'true'
      APP_ENV: 'production'
      APP_URL: 'https://rel.zah.rocks'
      APP_TRUSTED_PROXIES: '172.18.0.4'
      DB_HOST: 'mysql'
      DB_DATABASE: 'monica'
      DB_USERNAME: 'homestead'
    volumes:
      - "${COMPOSE_ROOT}/data/monica/:/var/www/html/storage/"
    ports:
      - "80"
    depends_on:
      - eas
      - mysql
      - traefik
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.monicahq.rule=Host(`rel.zah.rocks`)"
      - "traefik.http.routers.monicahq.entrypoints=websecure"
      - 'traefik.http.routers.monicahq.middlewares=monicahq'
      - "traefik.http.routers.monicahq.tls.certresolver=myresolver"

      - "traefik.http.middlewares.monicahq.forwardauth.trustForwardHeader=true"
      - "traefik.http.middlewares.monicahq.forwardauth.authResponseHeaders=X-Userinfo, X-Id-Token, X-Access-Token, Authorization"
      - "traefik.http.middlewares.monicahq.forwardauth.address=https://eas.zah.rocks/verify?config_token=%2BihV6%2F9CcXNCAOoc4grrmOmyxW0Xnbh0n8sY9qcgptvi1ct1bT857LxZBuctz8Qd%2BxSuhciOSvwxe66pmbl0uTG0WxZkoh5lygIvqdYQQ70i8%2FpUBVF91JTHWURDPHnrnT7EmJLcc2hr%2FRwzRyVLe7vhla86q0nzeQGgjcRksFeNpE62GCGjT0IYKN67Wm6KGPpZXSShwnW617TbpBVbmQ1DoUP0LbJPGKycVSPiv4USGLx7WuwiobmWoeABKcekm574mYthy8RMho6tJibeZq6fDE9%2BeyQf4by3n3rhOdOOnzGexKt6MyPUEcm4Bs%2By5Eg0FnxwoY3nzbMLdsK8nMDRv%2FcaIoPxZAAIQ9hP4WEjwM2hqQat7zZUuqAPTIqfw9Z1uvqKpJNe0fVY%2FwkhjvtDn1Mi15I27CrMeLp08r7U5ZxHA%2BxJ2WJja6ImotWyaJn4Ks1ANQ05z%2Fyjaunuds5rBUaIYUBJFEcv3fEifTnQ6qB6I25PxBLbie5Iy%2BP6MYkTNihrxRRZyAnaiP8Ggh5eSsCwpygb0gjapsRlc%2FwbO0N1GcBt8ROLQ%2FYoRy33uRlnsFjbqh8ZH6TzlPf1SNL8%2BHgDOfh3A4AnK5fjp2OvNMJ5BE5soyf9h%2Bcxob%2BiYMvGpYWkzXr%2FtF6YNs%2BopRBdblXFeFlm31a%2FLA29eVv27AaJMTTz8w71ABm4ozHa7HJofCDZHxlxLQEiTPEavwiV44K71HXfTAackyql8KmpQ1UiGVaBToOwj5U%2FMndHsaHwBnHug7G4qJLAHp2WaZIhTzZv62bMAVOQGFAFqoDMm%2ByB3kswzC%2BH4LP3ZREyclnS1N9cU3g01OO38Te3hGSeNrzCr9gRzykHR6N0%2FfL6FJlFj6EFE9zj2y0T5VzAGKryhmxjjhbuwEHpVcIsS1h3DKvY9vOvvVDFBlE2zzomjbRYaRU2%2FbQKWsPZCeJ7fma%2BdweLKIAhnE3j4RRNZhVGhpBbQXT%2BgmZozG9lLpIZOVIN8D8V2QLrFUj4OU758DyyBN6AcImhwAqNRqLC1UVdVEGNWnsbHF6sfOt9JZzJR71UUHU4I19f43N%2BPfhZQ%2BiffSQRE6tOGqE3vOl50wI7DQFmuPEGBHFhb8ao3Ox2uYNXFF0DVdAb%2B094iT9ReIssScqBqZWR28eHeZEs6J3AFZ7Zhfya9TOjYt%2FR955mZkeKFGJJU9ohUT0uz9bK90lsoB%2Fm17AU49VVAgMLy1CCc%2BKT3TxhGKW0dmQzliDIx%2FKtCeLGfK%2FFgVB%2F4cRPbKb7mOB4E89TAq81mRouJdW%2F2S1shG9s9M1eo8yLDBslK54kKywM9rQPMlTfcmupXi3Etdn%2FeNuCQUvD2BvcjXjRuhXLzvRcQa8pXlbYzgAT3DKu6%2FJb78YnN5owGCuYRh8949L5bWB3DNrvK3JliT%2BnaSPLUks6B6Dqr5pvrePjvCLHbgPQwzeLvyW8KmDdVJ4DTNcXQvIfTsuuM%2FKUu898VD2REPwC%2F7UjLXwFBLdb3932JK0PAkdbZd0aNYDAvoTxocW5UaJ5b7imLfMFk6BB6CZ7lA2lWGfA%2FdNxCoy%2BBI44%2FhKKqIg%2B2mcULlNdKseaOoRzcr9KI39InLJShM8zOXV5ZUx84V9tYq61r8r4gySP9cBrj4DerXk3K%2BJviujq0vq9m8RBwJPxSLHdC2fvYgss3UfiZ0Ekm7MeqIwl2hQOISjfScC3DBgm7KI%2FnGQ2ytle4vMbfVqrsCqDnRkJpO6Y6li2n1r5Nr8oQJEd2ExvIMstUlwBY1ijKUCIZ0lIoCpl8gCX2ewQIPItf5pKvOEmuZp9h9enN6TSGd5%2FXLtGpEFEDctMnv8vsAPKOEAwoKTBvs%2BDXTcWR5FigabcfRwPcKEkaaFQ4uzS%2FNaAFwzoIFTAh3m%2BcJ4ZWLAWJ9gildA3C%2BXSBglFf8KIEAPW91%2BWFvHZq3P6C%2FSV6%2B7KkNJSV1z2n1fE19oHrYnQr7zN9Yj8spCN7pU92iIg9rYF3FEiOAVvqMPOL0z89J33U8AVdcYNpFFMFAuFCS8CWS6mh831SzCXQzGbCYc5Sg%3D%3D"
