---

services:
  sheetable:
    # 2023-01-06
    image: vallezw/sheetable:v0.8@sha256:8e725e6222c9b5fcdcb69091bcb747fb66960904bb9a1e5ecbae6c3d18b86b6b
    environment:
      CONFIG_PATH: '/data'
      DB_DRIVER: 'postgres'
      DB_HOST: 'postgres'
      DB_PORT: 5432
      PORT: 8000
      # https://sheetable.net/docs/configuration/
    env_file:
      - "~/docker/services/sheetable/secret.env"
    ports:
      - "8000"
    volumes:
      - "~/docker/data/sheetable/:/data/"
    restart: unless-stopped
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sheetmusic.rule=Host(`sheetmusic.zah.rocks`)"
      - "traefik.http.routers.sheetmusic.entrypoints=websecure"
      - "traefik.http.routers.sheetmusic.tls.certresolver=myresolver"
