version: '3.7'

services:
  sheetable:
    image: vallezw/sheetable:v0.3@sha256:acb7e2e06c1d20f6255e5311d1c38c92412ad05eb9a56ad1acb6bf967e3bd6c3
    environment:
      CONFIG_PATH: '/data'
      DB_DRIVER: 'postgres'
      DB_HOST: 'postgres'
      DB_USER: 'sheetable'
      DB_NAME: 'sheetable'
      DB_PORT: 5432
      PORT: 8000
      # https://sheetable.net/docs/configuration/
    env_file:
      - "/mnt/data/services/sheetable/secret.env"
    ports:
      - "8000"
    volumes:
      - "/mnt/data/sheetable/:/data/"
    restart: unless-stopped
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sheetmusic.rule=Host(`sheetmusic.zah.rocks`)"
      - "traefik.http.routers.sheetmusic.entrypoints=websecure"
      - "traefik.http.routers.sheetmusic.tls.certresolver=myresolver"
