---
- name: check for mcrcon tarfile on remote box
  stat:
    path: '{{ mcrcon_download_dir }}/{{ mcrcon_tarfile }}'
    checksum_algorithm: sha256
  register: remote_mcrcon_tarfile
  ignore_errors: yes

- name: assert existing mcrcon matches checksum
  assert:
    that:
      - remote_mcrcon_tarfile.stat.checksum == mcrcon_sha256sum
    msg: 'Checksum failed: {{ remote_mcrcon_tarfile.stat.checksum }} != {{ mcrcon_sha256sum }}'
  when: remote_mcrcon_tarfile.stat.exists

- name: ensure ansible tmp downloads dir exists
  ansible.builtin.file:
    path: "{{ mcrcon_download_dir }}"
    state: 'directory'
    owner: 'root'
    group: 'root'

- name: download mcrcon
  get_url:
    url: 'https://github.com/Tiiffi/mcrcon/releases/download/v0.7.2/mcrcon-0.7.2-linux-x86-64.tar.gz'
    dest: '{{ mcrcon_download_dir }}/{{ mcrcon_tarfile }}'
    checksum: 'sha256:{{ mcrcon_sha256sum }}'
    force: no
    timeout: 30
    mode: 'u=rw,go=r'
  when: not remote_mcrcon_tarfile.stat.exists

- name: install mcrcon
  become: yes
  unarchive:
    src: '{{ mcrcon_download_dir }}/{{ mcrcon_tarfile }}'
    dest: '/usr/bin/'
    copy: no
    owner: root
    group: root
    mode: 'u=rwx,go=rx'
