version: '3.7'

services:
  radicale:
    # 01-30-22
    image: tomsquest/docker-radicale:3.1.3.0
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
      - CHOWN
      - KILL
    volumes:
      - "/mnt/data/radicale:/data"
      - "/mnt/data/services/radicale/config:/etc/radicale/config:ro"
      - "/mnt/data/services/radicale/users:/etc/radicale/users:ro"
    ports:
      - "5232"
    read_only: true
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radicale.rule=Host(`cal.zah.rocks`)"
      - "traefik.http.routers.radicale.entrypoints=websecure"
      - "traefik.http.routers.radicale.tls.certresolver=myresolver"
