version: '3.7'

services:
  photostructure:
    image: 'photostructure/server:v2.1.0-alpha.7@sha256:ccd309179a5aa61d7601752bc79bf6304cc4257c907a614812ddaef8f422cb54'
    restart: 'unless-stopped'
    stop_grace_period: '2m'
    environment:
      # https://photostructure.com/faq/environment-variables
      PUID: 1005
      PGID: 1005
      TZ: 'America/New_York'
      PS_TRUST_PROXY: '172.0.0.0/8'
      PS_HTTP_PORT: 1787
      PS_LOG_LEVEL: 'error'
      PS_SCAN_ALL_DRIVES: 'false'
      PS_LOG_COMPRESSION: 'true'
      #PS_CPU_LOAD_PERCENT: ''
      PS_START_PAUSED: 'true'
      #PS_SCAN_PATHS:"/var/a:/var/b"
    ports:
      - "1787"
    volumes:
      - "~/docker/data/logs/photostructure/:/ps/logs/:rw"
      - "~/docker/data/photostructure/config/:/ps/config/:rw"
      - "~/docker/data/photostructure/media/:/ps/library/:rw"
      - "~/docker/data/photostructure/.cache/:/ps/tmp/:rw"
      - "/mnt/eagle/backups/photos/andrew/:/var/andrew-pictures-1/:rw"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.photostructure.rule=Host(`photos.zah.rocks`)"
      - "traefik.http.routers.photostructure.entrypoints=websecure"
      - "traefik.http.routers.photostructure.tls.certresolver=myresolver"
      - 'traefik.http.routers.photostructure.middlewares=eas-default'
