version: '3.7'

services:
  navidrome:
    # 01-22-2022
    image: deluan/navidrome:0.47.5@sha256:4114446451d1122717c33e46339bb9e36ff6568c7c2f92a1a4e008648b49a2bf
    environment:
      ND_PORT: 4533
      ND_MUSICFOLDER: /music
      ND_DATAFOLDER: /data
      ND_SCANSCHEDULE: '@every 1m'
      ND_COVERJPEGQUALITY: 85
      ND_TRANSCODINGCACHESIZE: "500MB"
      ND_LOGLEVEL: 'info'
      # enable things we want
      ND_ENABLEDOWNLOADS: 'true'
      # disable for performance fix
      ND_DEVACTIVITYPANEL: 'false'
      # TODO: spotify
      #ND_SPOTIFY_ID:
      #ND_SPOTIFY_SECRET:
      # disable things we don't need / want
      ND_AUTOIMPORTPLAYLISTS: 'false'
      ND_ENABLEGRAVATAR: 'false'
      ND_ENABLESTARRATING: 'false'
      ND_LASTFM_ENABLED: 'false'
      # disable for security
      ND_ENABLETRANSCODINGCONFIG: 'false'
    ports:
        - "4533"
    volumes:
      - "/mnt/data/navidrome:/data"
      - "/mnt/media/music:/music"
    restart: unless-stopped
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.navidrome.rule=Host(`music.zah.rocks`)"
      - "traefik.http.routers.navidrome.entrypoints=websecure"
      - "traefik.http.routers.navidrome.tls.certresolver=myresolver"
