version: '3.7'

services:
  homer:
    # 09-15-21
    image: b4bz/homer:21.09.2
    environment:
      UID: 1000
      PID: 1000
    ports:
        - "8080"
    volumes:
      - "${COMPOSE_ROOT}/data/homer/:/www/assets/"
    read_only: true
    restart: unless-stopped
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homer.rule=Host(`homer.lilac.zah.rocks`)"
      - "traefik.http.routers.homer.entrypoints=websecure"
      - "traefik.http.routers.homer.tls.certresolver=myresolver"
