postgres_db: '{{ vault_postgres_db }}'
postgres_user: '{{ vault_postgres_user }}'
postgres_password: '{{ vault_postgres_password }}'

smtp_user: '{{ v_smtp_user }}'
smtp_port: '{{ v_smtp_port }}'
smtp_host: '{{ v_smtp_host }}'

smtp_rallly_email: '{{ v_smtp_rallly_email }}'
smtp_rallly_password: '{{ v_smtp_rallly_password }}'
smtp_healthchecks_password: '{{ v_smtp_healthchecks_password }}'

pg_bitwarden_password: '{{ v_pg_bitwarden_password }}'
pg_healthchecks_password: '{{ v_pg_healthchecks_password }}'
pg_hedgedoc_password: '{{ v_pg_hedgedoc_password }}'
pg_keycloak_password: '{{ v_pg_keycloak_password }}'
pg_rallly_password: '{{ v_pg_rallly_password }}'

ntfy_smtp_user: '{{ v_ntfy_smtp_user }}'
ntfy_smtp_password: '{{ v_ntfy_smtp_password }}'

keycloak_admin_password: '{{ v_keycloak_admin_password }}'
kc_hedgedoc_client_secret: '{{ v_kc_hedgedoc_client_secret }}'

lam_password: '{{ v_lam_password }}'
ldap_admin_username: '{{ v_ldap_admin_username }}'
ldap_admin_password: '{{ v_ldap_admin_password }}'

ldap_auth:
  server_uri: 'ldap://localhost:1389'
  bind_dn: 'cn={{ ldap_admin_username }},dc=zah,dc=rocks'
  bind_pw: '{{ ldap_admin_password }}'

ldap_users: '{{ v_ldap_users }}'

radicale_hashed_password: '{{ v_radicale_hashed_password }}'

rallly_secret_password: '{{ v_rallly_secret_password }}'

healthchecks_superuser_email: '{{ v_healthchecks_superuser_email }}'
healthchecks_secret_key: '{{ v_healthchecks_secret_key }}'

mariadb_user: '{{ v_mariadb_user }}'
mariadb_password: '{{ v_mariadb_password }}'
mariadb_root_password: '{{ v_mariadb_root_password }}'

sheetable: '{{ v_sheetable }}'
kanboard: '{{ v_kanboard }}'
misskey: '{{ v_misskey }}'
gitea: '{{ v_gitea }}'
ghost: '{{ v_ghost }}'
goatcounter: '{{ v_goatcounter }}'
