version: '3.7'

services:
  filestash:
    # 03-23-21
    image: machines/filestash:e02267d
    environment:
      FILESTASH_DOMAIN: files.zah.rocks
    volumes:
      - "${COMPOSE_ROOT}/data/filestash/state/:/lapp/data/state/:rw"
      - "${COMPOSE_ROOT}/data/filestash/files/:/files/:rw"
    restart: unless-stopped
    depends_on:
      - eas
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.filestash.rule=Host(`files.zah.rocks`)"
      #- 'traefik.http.routers.filestash.middlewares=eas-default'
      - "traefik.http.routers.filestash.entrypoints=websecure"
      - "traefik.http.routers.filestash.tls.certresolver=myresolver"
