version: '3.7'

services:
  homeassistant:
    image: homeassistant/home-assistant:stable
    environment:
      PUID: 1000
      PGID: 1000
      TZ: 'America/New_York'
   #devices:
      #- /dev/ttyUSB0
      #- /dev/ttyUSB1
    network_mode: host
    restart: unless-stopped
    depends_on:
      - eas
      - traefik
    volumes:
      - "/mnt/data/homeassistant/config:/config"
      - "/etc/localtime:/etc/localtime:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.port=8123"
      - "traefik.http.routers.homeassistant.rule=Host(`home.genessee.zah.rocks`)"
      - "traefik.http.routers.homeassistant.entrypoints=websecure"
      - "traefik.http.routers.homeassistant.tls.certresolver=myresolver"
      - "traefik.http.services.homeassistant.loadBalancer.server.port=8123"
      - 'traefik.http.routers.homeassistant.middlewares=eas-default'
