version: '3.7'

services:
  searx:
    # 6/1/21
    image: searx/searx:1.0.0-141-02675639
    restart: unless-stopped
    ports:
      - "8080"
    environment:
      BASE_URL: 'https://searx.zah.rocks'
      INSTANCE_NAME: 'searx.zah.rocks'
    volumes:
      - "/mnt/data/searx/:/etc/searx/"
    restart: unless-stopped
    depends_on:
      - traefik
      - postgres
      - eas
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.searx.rule=Host(`searx.zah.rocks`)"
      - "traefik.http.routers.searx.entrypoints=websecure"
      - "traefik.http.routers.searx.tls.certresolver=myresolver"
      - 'traefik.http.routers.searx.middlewares=eas-default'
