version: '3.7'

services:
  miniflux:
    build: 
      context: "/mnt/data/services/miniflux"
    environment:
      LISTEN_ADDR: '0.0.0.0:8080'
    env_file:
      - "/mnt/data/services/miniflux/secret.env"
    ports:
      - "8080"
    restart: unless-stopped
    depends_on:
      - eas
      - postgres
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.miniflux.rule=Host(`rss.zah.rocks`)"
      - "traefik.http.routers.miniflux.entrypoints=websecure"
      - 'traefik.http.routers.miniflux.middlewares=eas-default'
      - "traefik.http.routers.miniflux.tls.certresolver=myresolver"
