---

#################
### env files ###
#################

- name: overall secret.env template
  ansible.builtin.template:
    src: secret.env.j2
    dest: '~/docker/secret.env'
    owner: 'ansible'
    group: 'ansible'
    mode: '0400'

- name: traefik rules.toml template
  ansible.builtin.template:
    src: traefik/rules.toml.j2
    dest: '~/docker/services/traefik/rules.toml'
    owner: 'ansible'
    group: 'ansible'
    mode: '0400'

- name: traefik secret.env template
  ansible.builtin.template:
    src: traefik.env.j2
    dest: '~/docker/services/traefik/secret.env'
    owner: 'ansible'
    group: 'ansible'
    mode: '0400'

- name: atuin secret.env template
  ansible.builtin.template:
    src: atuin.env.j2
    dest: '~/docker/services/atuin/secret.env'
    owner: 'ansible'
    group: 'ansible'
    mode: '0400'

- name: hedgedoc secret.env template
  ansible.builtin.template:
    src: hedgedoc.env.j2
    dest: '~/docker/services/hedgedoc/secret.env'
    owner: 'ansible'
    group: 'ansible'
    mode: '0400'

- name: memos secret.env template
  ansible.builtin.template:
    src: memos.env.j2
    dest: '~/docker/services/memos/secret.env'
    owner: 'ansible'
    group: 'ansible'
    mode: '0400'

- name: huginn secret.env template
  ansible.builtin.template:
    src: huginn.env.j2
    dest: '~/docker/services/huginn/secret.env'
    owner: 'ansible'
    group: 'ansible'
    mode: '0400'

- name: keycloak secret.env template
  ansible.builtin.template:
    src: keycloak.env.j2
    dest: '~/docker/services/keycloak/secret.env'
    owner: 'ansible'
    group: 'ansible'
    mode: '0400'

- name: keycloak25 secret.env template
  ansible.builtin.template:
    src: keycloak25.env.j2
    dest: '~/docker/services/keycloak25/secret.env'
    owner: 'ansible'
    group: 'ansible'
    mode: '0400'

- name: kanboard secret.env template
  ansible.builtin.template:
    src: kanboard.env.j2
    dest: '~/docker/services/kanboard/secret.env'
    owner: 'ansible'
    group: 'ansible'
    mode: '0600'

- name: mariadb secret.env template
  ansible.builtin.template:
    src: mariadb.env.j2
    dest: '~/docker/services/mariadb/secret.env'
    owner: 'ansible'
    group: 'ansible'
    mode: '0400'

- name: homebox secret.env template
  ansible.builtin.template:
    src: homebox.env.j2
    dest: '~/docker/services/homebox/secret.env'
    owner: 'ansible'
    group: 'ansible'
    mode: '0400'

- name: postgres secret.env template
  ansible.builtin.template:
    src: postgres.env.j2
    dest: '~/docker/services/postgres/secret.env'
    owner: 'ansible'
    group: 'ansible'
    mode: '0400'

- name: vaultwarden secret.env template
  ansible.builtin.template:
    src: vaultwarden.env.j2
    dest: '~/docker/services/vaultwarden/secret.env'
    owner: 'ansible'
    group: 'ansible'
    mode: '0400'

- name: openldap secret.env template
  ansible.builtin.template:
    src: openldap.env.j2
    dest: '~/docker/services/openldap/secret.env'
    owner: 'ansible'
    group: 'ansible'
    mode: '0400'

- name: external-auth-server secret.env template
  ansible.builtin.template:
    src: eas.env.j2
    dest: '~/docker/services/external-auth-server/secret.env'
    owner: 'ansible'
    group: 'ansible'
    mode: '0400'

- name: rallly secret.env template
  ansible.builtin.template:
    src: rallly.env.j2
    dest: '~/docker/services/rallly/secret.env'
    owner: 'ansible'
    group: 'ansible'
    mode: '0400'

- name: healthchecks secret.env template
  ansible.builtin.template:
    src: healthchecks.env.j2
    dest: '~/docker/services/healthchecks/secret.env'
    owner: 'ansible'
    group: 'ansible'
    mode: '0400'

- name: sheetable secret.env template
  ansible.builtin.template:
    src: sheetable.env.j2
    dest: '~/docker/services/sheetable/secret.env'
    owner: 'ansible'
    group: 'ansible'
    mode: '0400'

- name: goatcounter secret.env template
  ansible.builtin.template:
    src: goatcounter.env.j2
    dest: '~/docker/services/goatcounter/secret.env'
    owner: 'ansible'
    group: 'ansible'
    mode: '0400'

- name: misskey secret.env template
  ansible.builtin.template:
    src: misskey.env.j2
    dest: '~/docker/services/misskey/secret.env'
    owner: 'ansible'
    group: 'ansible'
    mode: '0400'

###################
### other files ###
###################

- name: dashy conf.yml template
  ansible.builtin.template:
    src: dashy.conf.yml.j2
    dest: '~/docker/services/dashy/conf.yml'
    owner: 'ansible'
    group: 'ansible'
    mode: '0644'

- name: misskey default.yml
  ansible.builtin.template:
    src: misskey.yml.j2
    dest: '~/docker/services/misskey/default.yml'
    owner: 'ansible'
    group: 'ansible'
    mode: '0400'

- name: komga application.yml template
  ansible.builtin.template:
    src: komga.application.yml.j2
    dest: '~/docker/services/komga/application.yml'
    owner: 'ansible'
    group: 'ansible'
    mode: '0600'

- name: romm secret.env template
  ansible.builtin.template:
    src: romm.env.j2
    dest: '~/docker/services/romm/secret.env'
    owner: 'ansible'
    group: 'ansible'
    mode: '0400'

#- name: radicale users template
#  ansible.builtin.template:
#    src: radicale.users.j2
#    dest: '~/docker/services/radicale/users'
#    owner: 'ansible'
#    group: 'ansible'
#    mode: '0644'
