---

#################
### env files ###
#################

- name: secret.env template
  ansible.builtin.template:
    src: secret.env.j2
    dest: '~/docker/secret.env'
    owner: 'ansible'
    group: 'ansible'
    mode: '0400'

- name: rules.toml template
  ansible.builtin.template:
    src: traefik/rules.toml.j2
    dest: '~/docker/services/traefik/rules.toml'
    owner: 'ansible'
    group: 'ansible'
    mode: '0400'

- name: hedgedoc secret.env template
  ansible.builtin.template:
    src: hedgedoc.env.j2
    dest: '~/docker/services/hedgedoc/secret.env'
    owner: 'ansible'
    group: 'ansible'
    mode: '0400'

- name: keycloak secret.env template
  ansible.builtin.template:
    src: keycloak.env.j2
    dest: '~/docker/services/keycloak/secret.env'
    owner: 'ansible'
    group: 'ansible'
    mode: '0400'

- name: postgres secret.env template
  ansible.builtin.template:
    src: postgres.env.j2
    dest: '~/docker/services/postgres/secret.env'
    owner: 'ansible'
    group: 'ansible'
    mode: '0400'

- name: vaultwarden secret.env template
  ansible.builtin.template:
    src: vaultwarden.env.j2
    dest: '~/docker/services/vaultwarden/secret.env'
    owner: 'ansible'
    group: 'ansible'
    mode: '0400'

- name: openldap secret.env template
  ansible.builtin.template:
    src: openldap.env.j2
    dest: '~/docker/services/openldap/secret.env'
    owner: 'ansible'
    group: 'ansible'
    mode: '0400'

- name: external-auth-server secret.env template
  ansible.builtin.template:
    src: eas.env.j2
    dest: '~/docker/services/external-auth-server/secret.env'
    owner: 'ansible'
    group: 'ansible'
    mode: '0400'

###################
### other files ###
###################

- name: ntfy server.yml template
  ansible.builtin.template:
    src: ntfy.server.j2
    dest: '~/docker/services/ntfy/server.yml'
    owner: 'ansible'
    group: 'ansible'
    mode: '0400'

