---
- name: Ensure packages are installed
  become: 'yes'
  ansible.builtin.apt:
    name:
      - 'git'
    state: 'present'
    update_cache: 'yes'

- name: Clone the service-automation repo
  git:
    dest: '~/docker'
    clone: 'yes'
    update: 'yes'
    repo: "{{ github_repo_url }}"
