---

#################
### PILER ###
#################

- name: MARIADB - piler database
  community.mysql.mysql_db:
    login_host: 127.0.0.1
    login_port: 3307
    login_user: 'root'
    login_password: '{{ mariadb_root_password }}'
    name: piler
    state: absent

- name: MARIADB - piler user
  community.mysql.mysql_user:
    login_host: 127.0.0.1
    login_port: 3307
    login_user: 'root'
    login_password: '{{ mariadb_root_password }}'
    name: piler
    password: '{{ mdb_piler_password }}'
    state: absent
