---

#################
### BITWARDEN ###
#################

- name: PG - bitwarden database
  community.postgresql.postgresql_db:
    login_host: 127.0.0.1
    login_port: 5433
    login_user: '{{ postgres_user }}'
    login_password: '{{ postgres_password }}'
    name: bitwarden
    state: present

- name: PG - bitwarden user
  community.postgresql.postgresql_user:
    login_host: 127.0.0.1
    login_port: 5433
    login_user: '{{ postgres_user }}'
    login_password: '{{ postgres_password }}'
    db: bitwarden
    name: bitwarden
    password: '{{ pg_bitwarden_password }}'
    state: present

- name: PG - bitwarden privs
  community.postgresql.postgresql_privs:
    login_host: 127.0.0.1
    login_port: 5433
    login_user: '{{ postgres_user }}'
    login_password: '{{ postgres_password }}'
    db: postgres
    privs: ALL
    type: database
    obj: bitwarden
    role: bitwarden
    state: present

################
### HEDGEDOC ###
################

- name: PG - hedgedoc database
  community.postgresql.postgresql_db:
    login_host: 127.0.0.1
    login_port: 5433
    login_user: '{{ postgres_user }}'
    login_password: '{{ postgres_password }}'
    name: hedgedoc
    state: present

- name: PG - hedgedoc user
  community.postgresql.postgresql_user:
    login_host: 127.0.0.1
    login_port: 5433
    login_user: '{{ postgres_user }}'
    login_password: '{{ postgres_password }}'
    db: hedgedoc
    name: hedgedoc
    password: '{{ pg_hedgedoc_password }}'
    state: present

- name: PG - hedgedoc privs
  community.postgresql.postgresql_privs:
    login_host: 127.0.0.1
    login_port: 5433
    login_user: '{{ postgres_user }}'
    login_password: '{{ postgres_password }}'
    db: postgres
    privs: ALL
    type: database
    obj: hedgedoc
    role: hedgedoc
    state: present

################
### KEYCLOAK ###
################

- name: PG - keycloak database
  community.postgresql.postgresql_db:
    login_host: 127.0.0.1
    login_port: 5433
    login_user: '{{ postgres_user }}'
    login_password: '{{ postgres_password }}'
    name: keycloak
    state: present

- name: PG - keycloak user
  community.postgresql.postgresql_user:
    login_host: 127.0.0.1
    login_port: 5433
    login_user: '{{ postgres_user }}'
    login_password: '{{ postgres_password }}'
    db: keycloak
    name: keycloak
    password: '{{ pg_keycloak_password }}'
    state: present

- name: PG - keycloak privs
  community.postgresql.postgresql_privs:
    login_host: 127.0.0.1
    login_port: 5433
    login_user: '{{ postgres_user }}'
    login_password: '{{ postgres_password }}'
    db: postgres
    privs: ALL
    type: database
    obj: keycloak
    role: keycloak
    state: present

##############
### RALLLY ###
##############

- name: PG - rallly database
  community.postgresql.postgresql_db:
    login_host: 127.0.0.1
    login_port: 5433
    login_user: '{{ postgres_user }}'
    login_password: '{{ postgres_password }}'
    name: rallly
    state: present

- name: PG - rallly user
  community.postgresql.postgresql_user:
    login_host: 127.0.0.1
    login_port: 5433
    login_user: '{{ postgres_user }}'
    login_password: '{{ postgres_password }}'
    db: rallly
    name: rallly
    password: '{{ pg_rallly_password }}'
    state: present

- name: PG - rallly privs
  community.postgresql.postgresql_privs:
    login_host: 127.0.0.1
    login_port: 5433
    login_user: '{{ postgres_user }}'
    login_password: '{{ postgres_password }}'
    db: postgres
    privs: ALL
    type: database
    obj: rallly
    role: rallly
    state: present

####################
### HEALTHCHECKS ###
####################

- name: PG - healthchecks database
  community.postgresql.postgresql_db:
    login_host: 127.0.0.1
    login_port: 5433
    login_user: '{{ postgres_user }}'
    login_password: '{{ postgres_password }}'
    name: healthchecks
    state: present

- name: PG - healthchecks user
  community.postgresql.postgresql_user:
    login_host: 127.0.0.1
    login_port: 5433
    login_user: '{{ postgres_user }}'
    login_password: '{{ postgres_password }}'
    db: healthchecks
    name: healthchecks
    password: '{{ pg_healthchecks_password }}'
    state: present

- name: PG - healthchecks privs
  community.postgresql.postgresql_privs:
    login_host: 127.0.0.1
    login_port: 5433
    login_user: '{{ postgres_user }}'
    login_password: '{{ postgres_password }}'
    db: postgres
    privs: ALL
    type: database
    obj: healthchecks
    role: healthchecks
    state: present

####################
### SHEETABLE ###
####################

- name: PG - sheetable database
  community.postgresql.postgresql_db:
    login_host: 127.0.0.1
    login_port: 5433
    login_user: '{{ postgres_user }}'
    login_password: '{{ postgres_password }}'
    name: '{{ sheetable.db_name }}'
    state: present

- name: PG - sheetable user
  community.postgresql.postgresql_user:
    login_host: 127.0.0.1
    login_port: 5433
    login_user: '{{ postgres_user }}'
    login_password: '{{ postgres_password }}'
    db: '{{ sheetable.db_name }}'
    name: '{{ sheetable.db_username }}'
    password: '{{ sheetable.db_password }}'
    state: present

- name: PG - sheetable privs
  community.postgresql.postgresql_privs:
    login_host: 127.0.0.1
    login_port: 5433
    login_user: '{{ postgres_user }}'
    login_password: '{{ postgres_password }}'
    db: '{{ sheetable.db_name }}'
    privs: ALL
    type: database
    role: '{{ sheetable.db_username }}'
    state: present

################
### KANBOARD ###
################

- name: PG - kanboard database
  community.postgresql.postgresql_db:
    login_host: 127.0.0.1
    login_port: 5433
    login_user: '{{ postgres_user }}'
    login_password: '{{ postgres_password }}'
    name: '{{ kanboard.db.name }}'
    state: present

- name: PG - kanboard user
  community.postgresql.postgresql_user:
    login_host: 127.0.0.1
    login_port: 5433
    login_user: '{{ postgres_user }}'
    login_password: '{{ postgres_password }}'
    db: '{{ kanboard.db.name }}'
    name: '{{ kanboard.db.username }}'
    password: '{{ kanboard.db.password }}'
    state: present

- name: PG - kanboard privs
  community.postgresql.postgresql_privs:
    login_host: 127.0.0.1
    login_port: 5433
    login_user: '{{ postgres_user }}'
    login_password: '{{ postgres_password }}'
    db: '{{ kanboard.db.name }}'
    privs: ALL
    type: database
    role: '{{ kanboard.db.username }}'
    state: present

################
### misskey ###
################

- name: PG - misskey database
  community.postgresql.postgresql_db:
    login_host: 127.0.0.1
    login_port: 5433
    login_user: '{{ postgres_user }}'
    login_password: '{{ postgres_password }}'
    name: '{{ misskey.postgres.database }}'
    state: present

- name: PG - misskey user
  community.postgresql.postgresql_user:
    login_host: 127.0.0.1
    login_port: 5433
    login_user: '{{ postgres_user }}'
    login_password: '{{ postgres_password }}'
    db: '{{ misskey.postgres.database }}'
    name: '{{ misskey.postgres.username }}'
    password: '{{ misskey.postgres.password }}'
    state: present

- name: PG - misskey privs
  community.postgresql.postgresql_privs:
    login_host: 127.0.0.1
    login_port: 5433
    login_user: '{{ postgres_user }}'
    login_password: '{{ postgres_password }}'
    db: '{{ misskey.postgres.database }}'
    privs: ALL
    type: database
    role: '{{ misskey.postgres.username }}'
    state: present
