---

- name: PG - databases
  community.postgresql.postgresql_db:
    login_host: 127.0.0.1
    login_port: 5433
    login_user: '{{ postgres.user }}'
    login_password: '{{ postgres.password }}'
    name: '{{ item.db_name }}'
    state: present
  loop: '{{ z_services }}'

- name: PG - users
  community.postgresql.postgresql_user:
    login_host: 127.0.0.1
    login_port: 5433
    login_user: '{{ postgres.user }}'
    login_password: '{{ postgres.password }}'
    db: '{{ item.db_name }}'
    name: '{{ item.username }}'
    password: '{{ item.password }}'
    state: present
  loop: '{{ z_services }}'

- name: PG - privs
  community.postgresql.postgresql_privs:
    login_host: 127.0.0.1
    login_port: 5433
    login_user: '{{ postgres.user }}'
    login_password: '{{ postgres.password }}'
    db: postgres
    privs: ALL
    type: database
    state: present
    obj: '{{ item.db_name }}'
    role: '{{ item.username }}'
  loop: '{{ z_services }}'

- name: PG - extensions
  community.postgresql.postgresql_ext:
    login_host: 127.0.0.1
    login_port: 5433
    login_user: '{{ postgres.user }}'
    login_password: '{{ postgres.password }}'
    db: '{{ item.db_name }}'
    name: '{{ item.ext_name }}'
    state: 'present'
    cascade: true
  loop: '{{ z_extensions }}'

#- name: PG - privs - public schema
#  community.postgresql.postgresql_schema:
#    login_host: 127.0.0.1
#    login_port: 5433
#    login_user: '{{ postgres.user }}'
#    login_password: '{{ postgres.password }}'
#    #privs: ALL
#    schema: public
#    state: present
#    db: '{{ item.db_name }}'
#    owner: '{{ item.username }}'
#  loop: '{{ z_services }}'
