---

#################
### BITWARDEN ###
#################

- name: PG - bitwarden database
  community.postgresql.postgresql_db:
    login_host: 127.0.0.1
    login_port: 5433
    login_user: '{{ postgres_user }}'
    login_password: '{{ postgres_password }}'
    name: bitwarden
    state: present

- name: PG - bitwarden user
  community.postgresql.postgresql_user:
    login_host: 127.0.0.1
    login_port: 5433
    login_user: '{{ postgres_user }}'
    login_password: '{{ postgres_password }}'
    db: bitwarden
    name: bitwarden
    password: '{{ pg_bitwarden_password }}'
    state: present

- name: PG - bitwarden privs
  community.postgresql.postgresql_privs:
    login_host: 127.0.0.1
    login_port: 5433
    login_user: '{{ postgres_user }}'
    login_password: '{{ postgres_password }}'
    db: postgres
    privs: ALL
    type: database
    obj: bitwarden
    role: bitwarden
    state: present

################
### HEDGEDOC ###
################

- name: PG - hedgedoc database
  community.postgresql.postgresql_db:
    login_host: 127.0.0.1
    login_port: 5433
    login_user: '{{ postgres_user }}'
    login_password: '{{ postgres_password }}'
    name: hedgedoc
    state: present

- name: PG - hedgedoc user
  community.postgresql.postgresql_user:
    login_host: 127.0.0.1
    login_port: 5433
    login_user: '{{ postgres_user }}'
    login_password: '{{ postgres_password }}'
    db: hedgedoc
    name: hedgedoc
    password: '{{ pg_hedgedoc_password }}'
    state: present

- name: PG - hedgedoc privs
  community.postgresql.postgresql_privs:
    login_host: 127.0.0.1
    login_port: 5433
    login_user: '{{ postgres_user }}'
    login_password: '{{ postgres_password }}'
    db: postgres
    privs: ALL
    type: database
    obj: hedgedoc
    role: hedgedoc
    state: present

################
### KEYCLOAK ###
################

- name: PG - keycloak database
  community.postgresql.postgresql_db:
    login_host: 127.0.0.1
    login_port: 5433
    login_user: '{{ postgres_user }}'
    login_password: '{{ postgres_password }}'
    name: keycloak
    state: present

- name: PG - keycloak user
  community.postgresql.postgresql_user:
    login_host: 127.0.0.1
    login_port: 5433
    login_user: '{{ postgres_user }}'
    login_password: '{{ postgres_password }}'
    db: keycloak
    name: keycloak
    password: '{{ pg_keycloak_password }}'
    state: present

- name: PG - keycloak privs
  community.postgresql.postgresql_privs:
    login_host: 127.0.0.1
    login_port: 5433
    login_user: '{{ postgres_user }}'
    login_password: '{{ postgres_password }}'
    db: postgres
    privs: ALL
    type: database
    obj: keycloak
    role: keycloak
    state: present
