services:
  ghost:
    image: ghost:5-alpine@sha256:8ddb7bf9d37ee583eb183d54b210c9431016207498b02a23e472eda8602f6cce
    environment:
      NODE_ENV: 'production'
      url: 'https://blog.andrewzah.com'
      database__client: 'mysql'
      database__connection__host: 'mariadb'
    restart: unless-stopped
    env_file:
      - "~/docker/services/ghost/secret.env"
    volumes:
      - "~/docker/data/ghost/blog/:/var/lib/ghost/content/:z"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ghost.rule=Host(`blog.andrewzah.com`)"
      - "traefik.http.routers.ghost.entrypoints=websecure"
      - "traefik.http.routers.ghost.tls.certresolver=myresolver"
