---

services:
  # 2022-10-02
  redis:
    image: 'redis:7.0.5-alpine3.16@sha256:a9cc5c331a573b4e073cee01a100327800c11f111c8fff5a8209dea2d854768e'
    #command: 'redis-server /redis.conf'
    ports:
      - "6379"
      - "36379:6379"
    volumes:
      #- "~/docker/services/redis/redis.conf:/redis.conf"
      - "~/docker/data/redis/data/:/data/"
    restart: unless-stopped
