---
- name: Ensure old versions of Docker are not installed
  yum:
    name:
      - 'docker'
      - 'docker-client'
      - 'docker-client-latest'
      - 'docker-common'
      - 'docker-engine'
      - 'docker-latest'
      - 'docker-latest-logrotate'
      - 'docker-logrotate'
      - 'podman'
      - 'runc'
    state: 'absent'

- name: Ensure packages are installed
  yum:
    name:
      - 'yum-utils'
      #- 'ca-certificates'
      #- 'curl'
      #- 'gnupg'
    state: 'latest'
    update_cache: 'yes'

- name: add docker yum repo
  ansible.builtin.get_url:
    url: 'https://download.docker.com/linux/centos/docker-ce.repo'
    dest: '/etc/yum.repos.d/docker-ce.repo'

- name: install Docker
  yum:
    name:
      - 'containerd.io'
      - 'docker-buildx-plugin'
      - 'docker-ce'
      - 'docker-ce-cli'
      - 'docker-compose-plugin'
    state: 'latest'
  notify: restart docker

- name: ensure Docker is started and enabled at boot
  service:
    name: 'docker'
    state: 'started'
    enabled: true

- name: Ensure docker users are added to the docker group
  user:
    name: '{{ item }}'
    groups: 'docker'
    append: true
  with_items: '{{ docker_users }}'
