- name: Ensure old versions of Docker are not installed.
  become: yes
  apt:
    name:
      - docker
      - docker-engine
    state: absent

- name: Ensure packages are installed
  become: yes
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
    state: present
    update_cache: yes

- name: add docker GPG key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present

- name: Add Docker repository.
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present
    update_cache: true
