---
#- hosts: all
#  become_method: su
#  roles:
#    - base

#- hosts: telegraf
#  become_method: su
#  roles:
#    - telegraf

#- hosts: docker_services
#  become: 'yes'
#  roles:
#    - docker

#- hosts:
#    - docker.eagle.zah.arpa
#  roles:
#    - base
#    - z_docker_services

- hosts:
    - proxmox_eagle
  roles:
    - z_proxmox
  become: 'yes'

# - hosts:
#    - nominal.zah.arpa
#  roles:
#    - z_games

#- hosts: minecraft_test
#  become_method: su
#  roles:
#    #- java
#    - minecraft_fabric
