---
#- hosts: all
#  become_method: su
#  roles:
#    - base

#- hosts: telegraf
#  become_method: su
#  roles:
#    - telegraf

#- hosts: docker_services
#  become_method: su
#  roles:
#    - docker
#    - z_docker_services

- hosts: minecraft_test
  become_method: su
  roles:
    #- java
    - minecraft_fabric
