---
#- hosts: all
#  become_method: su
#  roles:
#    - base

#- hosts: telegraf
#  become_method: su
#  roles:
#    - telegraf

#- hosts: docker_services
#  become: 'yes'
#  roles:
#    - docker

#- hosts:
#    - docker.eagle.zah.arpa
#  roles:
#    - base
#  become: 'yes'

#- hosts:
#    - docker.eagle.zah.arpa
#  roles:
#    - z_docker_services

- hosts:
    - proxmox_eagle
  roles:
    - z_proxmox
  become: 'yes'

- hosts:
    - z_palmettotech
  roles:
    - z_palmettotech

#- hosts:
#    - 'games_prepare'
#  become: 'yes'
#  roles:
#  - role: 'docker'
#    vars:
#      docker_users:
#        - 'guest'
#  - role: 'z_prepare_games'

#- hosts:
#    - 'z_games'
#  roles:
#  - 'z_games'

#- hosts:
#    - games
#  roles:
#  - role: base
#    become_user: 'root'
#
#  - role: z_games
#    become_user: ansible

#- hosts: minecraft_test
#  become_method: su
#  roles:
#    #- java
#    - minecraft_fabric
