---

services:
  memos:
    image: docker.io/neosmemo/memos:0.22@sha256:6a3e76b69de8e0c425fbbfc67dbd7791dafe36fce6890ca100d0d339f85aed3b
    command: [ "./memos" ]
    environment:
      MEMOS_MODE: 'prod'
      MEMOS_DATA: '/data'
      MEMOS_ADDR: '0.0.0.0'
      MEMOS_PORT: '5230'
      MEMOS_DRIVER: 'postgres'
    env_file:
      - "~/docker/services/memos/secret.env"
    volumes:
      - "~/docker/data/memos/:/data/:rw"
    ports:
      - "5230"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.memos.rule=Host(`memos.zah.rocks`)"
      - "traefik.http.routers.memos.entrypoints=websecure"
      - "traefik.http.routers.memos.tls.certresolver=myresolver"
