version: '3.7'

services:
  memos:
    # 2024-03-10, v0.20.1
    image: docker.io/neosmemo/memos:latest@sha256:99fe58b680e843fbce91211dfdd8ac1e42c76c15aab2aeecd6beb0f50fc32432
    command:
      - "./memos"
      - "--mode prod"
      - "--addr memos.zah.rocks"
      - "--port 5230"
      - "--data /data"
      - "--driver postgres"
      - "--dsn postgres"
    ports:
      - "5230"
    volumes:
      - "~/docker/data/memos/:/data/:rw"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.memos.rule=Host(`memos.zah.rocks`)"
      - "traefik.http.routers.memos.entrypoints=websecure"
      - "traefik.http.routers.memos.tls.certresolver=myresolver"
