version: '3.7'

services:
  paperless-ng:
    # 09-13-21
    image: andrewzah/paperless@sha256:fc6e84e62ed18fff7f6b1095d4362e5d0eed971c328aedf9695662d7388e2450
    environment:
      # paperless[ng] config
      STATIC_ROOT: '/data/static'
      PAPERLESS_DATA_DIR: '/data/paperless'
      PAPERLESS_STATICDIR: '/data/static'
      PAPERLESS_CONSUMPTION_DIR: '/data/consume'
      PAPERLESS_MEDIA_ROOT: '/data/mediaroot'
      PAPERLESS_OCR_LANGUAGES: 'eng kor kor-vert chi-sim chi-sim-vert chi-tra chi-tra-vert jpn jpn-vert'
      PAPERLESS_TIME_ZONE: 'America/New_York'
      PAPERLESS_OCR_LANGUAGE: 'eng'
      # perms / other
      PUID: 1005
      PGID: 1005
      TZ: 'America/New_York'
      REDIS_URL: 'redis:36379'
    env_file:
      - "${COMPOSE_ROOT}/services/paperless/secret.env"
    ports:
        - "8000"
    volumes:
      - "/mnt/data/services/paperless-ng/data/:/data/"
    restart: unless-stopped
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.paperlessng.rule=Host(`ds.zah.rocks`)"
      - "traefik.http.routers.paperlessng.entrypoints=websecure"
      - "traefik.http.routers.paperlessng.tls.certresolver=myresolver"
