version: '3.7'

services:
  mariadb:
    image: mariadb:10-focal
    environment:
      MARIADB_ROOT_HOST: '%'
    env_file:
      - "/mnt/data/services/mariadb/secret.env"
    volumes:
      - "/mnt/data/mysql/:/var/lib/mysql/"
    ports:
      - "3306"
      - "3308:3306"
    restart: unless-stopped
