---

services:
  mariadb:
    hostname: mariadb
    image: mariadb:latest@sha256:a9547599cd87d7242435aea6fda22a9d83e2c06d16c658ef70d2868b3d3f6a80
    ports:
      - '3306'
      - '3307:3306'
    env_file:
      - "~/docker/services/mariadb/secret.env"
    volumes:
      - "~/docker/data/mariadb/:/var/lib/mysql/:rw"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 30s
      start_interval: 10s
      interval: 10s
      timeout: 5s
      retries: 5
