version: '3.7'

services:
  podgrab:
    # 09-20-21
    image: akhilrex/podgrab:latest@sha256:29fddccdce800427cdaa33412cefdfcfbba8ad5f0ded90d2d08e0f026a0517cf
    environment:
      CHECK_FREQUENCY: 240
    ports:
        - "8080"
    volumes:
      - "/mnt/data/podgrab/assets/:/assets/"
      - "/mnt/data/podgrab/config/:/config/"
    read_only: true
    restart: unless-stopped
    depends_on:
      - eas
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.podgrab.rule=Host(`podcasts.zah.rocks`)"
      - "traefik.http.routers.podgrab.entrypoints=websecure"
      - 'traefik.http.routers.podgrab.middlewares=eas-default'
      - "traefik.http.routers.podgrab.tls.certresolver=myresolver"
