---

services:
  com-andrewzah:
    # 2025-01-14
    image: docker.io/andrewzah/com-andrewzah:latest@sha256:ccb98918a56a5382694905c8c1f8433ebbc37f3a39af6038999a65b277d1ebb2
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.andrewzahcom.rule=Host(`andrewzah.com`)"
      - "traefik.http.routers.andrewzahcom.entrypoints=websecure"
      - "traefik.http.routers.andrewzahcom.tls.certresolver=cloudflare"
