services:
  com-andrewzah:
    # 2024-03-14
    image: docker.io/andrewzah/personal_site:latest@sha256:f2961c4c843f0a9b3301dbc994d1025ccd050bc4c68a1080870e181863084e28
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.andrewzahcom.rule=Host(`andrewzah.com`)"
      - "traefik.http.routers.andrewzahcom.entrypoints=websecure"
      - "traefik.http.routers.andrewzahcom.tls.certresolver=myresolver"
